#
# Default values for mrmat-prometheus

#
# Traffic Routing

httproute:
  enabled: true
  name: mrmat-prometheus-httproute
  hostnames:
  - mrmat-prometheus.local
  parents:
  - name: istio-ingress
    namespace: edge

#
# Dependency Chart overrides

prometheus:
  serviceAccounts:
    server:
      create: true
      name: mrmat-prometheus-svc
#  commonMetaLabels:
#    app.kubernetes.io/part-of: mrmat-prometheus
  server:
    ingress:
      enabled: false
    persistentVolume:
      size: 3Gi
    podLabels:
      sidecar.istio.io/inject: "true"
    service:
      enabled: true
