---
- name: Destroy a cluster
  hosts: localhost
  tasks:
  - name: Destroy the cluster
    kind_cluster:
      name: "{{ cluster.name }}"
      tool_kind: "{{ host.tool.kind.path }}"
      state: absent
