---
- name: Apply the cluster configuration
  hosts: localhost
  tasks:

  # This will fail if we use a local DNS server and haven't pointed to it yet
  - name: Upload the Helm charts to the local registry
    ansible.builtin.command:
      cmd: |
        {{ host.tool.helm.path }} push 
        {{ host.tool.helm.packaged_chart_path }}/{{ item }}-{{ host.tool.helm.chart_version }}.tgz 
        oci://{{ host.registry.name }}.{{ host.dns.zone }}:{{ host.registry.host_port | int }}/kube-eng
    loop:
    - kube-eng-cilium
    - kube-eng-istio
    - kube-eng-cert-manager
    - kube-eng-prometheus
    - kube-eng-edge
    - kube-eng-loki
    - kube-eng-alloy
    - kube-eng-grafana
    - kube-eng-kiali

  - name: Create the cluster
    block:
    - name: Create a client scope for sanitised role memberships
      community.general.keycloak_clientscope:
        auth_keycloak_url: "https://{{ host.idp.name }}.{{ host.dns.zone }}:{{ host.idp.host_port }}"
        auth_realm: master
        auth_username: admin
        auth_password: "{{ admin_password }}"
        name: kube-eng-kubernetes-roles
        description: Adds Kubernetes roles to id tokens
        protocol: openid-connect
        protocol_mappers:
        - config:
            access.token.claim: true
            claim.name: "roles"
            id.token.claim: true
            introspection.token.claim: true
            lightweight.claim: false
            userinfo.token.claim: true
            jsonType.label: String
            multivalued: true
            usermodel.clientRoleMapping.clientId: "{{ cluster.oidc.client_id }}"
          name: "client roles"
          protocol: openid-connect
          protocolMapper: oidc-usermodel-client-role-mapper
        state: present
        validate_certs: true
    - name: Register the cluster in the IDP
      community.general.keycloak_client:
        auth_keycloak_url: "https://{{ host.idp.name }}.{{ host.dns.zone }}:{{ host.idp.host_port }}"
        auth_realm: master
        auth_username: admin
        auth_password: "{{ admin_password }}"
        client_id: "{{ cluster.oidc.client_id }}"
        name: "{{ cluster.oidc.client_id }}"
        description: "Kube Eng :: Kubernetes Cluster"
        enabled: true
        protocol: openid-connect
        public_client: false
        client_authenticator_type: client-secret
        secret: "{{ admin_password }}"
        standard_flow_enabled: true
        implicit_flow_enabled: false
        direct_access_grants_enabled: true
        default_client_scopes:
        - email
        - offline_access
        - profile
        - kube-eng-kubernetes-roles
        validate_certs: true
    - name: Register the cluster viewer role in the IDP
      community.general.keycloak_role:
        auth_keycloak_url: "https://{{ host.idp.name }}.{{ host.dns.zone }}:{{ host.idp.host_port }}"
        auth_realm: master
        auth_username: admin
        auth_password: "{{ admin_password }}"
        name: kube-eng-viewer
        description: "Kube Eng :: Kubernetes Viewers"
        client_id: "{{ cluster.oidc.client_id }}"
        state: present
        validate_certs: true
    - name: Register the cluster admin role in the IDP
      community.general.keycloak_role:
        auth_keycloak_url: "https://{{ host.idp.name }}.{{ host.dns.zone }}:{{ host.idp.host_port }}"
        auth_realm: master
        auth_username: admin
        auth_password: "{{ admin_password }}"
        name: kube-eng-admin
        description: "Kube Eng :: Kubernetes Administrators"
        client_id: "{{ cluster.oidc.client_id }}"
        state: present
        validate_certs: true
    - name: Template the cluster configuration
      ansible.builtin.import_role:
        name: kind_configuration
      vars:
        control_plane_nodes: "{{ cluster.control_plane_nodes | int }}"
        worker_nodes: "{{ cluster.worker_nodes | int }}"
        cluster_name: "{{ cluster.name }}"
        directory: "{{ host.tool.kind.config_path }}"
        ca_file_path: "{{ host.pki.ca_path }}"
        airgap_registry_name: "{{ host.registry.name }}"
        pod_subnet_cidr: "{{ cluster.pod_subnet_cidr }}"
        service_subnet_cidr: "{{ cluster.service_subnet_cidr }}"
        cni: "{{ cluster.cni.kind }}"
        oidc_discovery_url: "https://{{ host.idp.name }}.kind:{{ host.idp.port }}/realms/master/.well-known/openid-configuration"
        oidc_issuer_url: "{{ cluster.oidc.issuer_url }}"
        oidc_client_id: "{{ cluster.oidc.client_id }}"
        oidc_username_claim: "{{ cluster.oidc.username_claim }}"
        oidc_groups_claim: "{{ cluster.oidc.groups_claim }}"
    - name: Deploy the cluster
      kind_cluster:
        cluster_name: "{{ cluster.name }}"
        config_file: "{{ host.tool.kind.config_path }}/config.yaml"
        tool_kind: "{{ host.tool.kind.path }}"
        state: present

  - name: Apply the ServiceMonitor CRD
    kubernetes.core.k8s:
      state: present
      apply: true
      src: "{{ preheat_path }}/servicemonitor-crd.yaml"
      server_side_apply:
        field_manager: ansible
      wait: true

  - name: Apply the PodMonitor CRD
    kubernetes.core.k8s:
      state: present
      apply: true
      src: "{{ preheat_path }}/podmonitor-crd.yaml"
      server_side_apply:
        field_manager: ansible
      wait: true

    # Note: This should not run at the same time as cloud-provider-kind, as it will create
    # a conflict for the field-manager.
  - name: Apply the Gateway API CRDs
    kubernetes.core.k8s:
      state: present
      apply: true
      src: "{{ preheat_path }}/gateway-api-crds.yaml"
      server_side_apply:
        field_manager: ansible
      wait: true

  - name: Deploy Cilium CNI, if enabled
    when: "cluster.cni.kind == 'cilium'"
    block:
    - name: Deploy Cilium
      kubernetes.core.helm:
        name: cilium
        create_namespace: true
        release_namespace: cilium
        chart_ref: "oci://{{ host.registry.name }}.{{ host.dns.zone }}:{{ host.registry.host_port | int }}/kube-eng/kube-eng-cilium"
        chart_version: "{{ host.tool.helm.chart_version }}"
        binary_path: "{{ host.tool.helm.path }}"
        wait: true
        values:
          cluster:
            name: "{{ cluster.name }}"
            edge:
              kind: "{{ cluster.edge.kind }}"
              fqdn: "{{ cluster.cni.hostname }}.{{ host.dns.zone }}"
              gateway:
                name: "{{ cluster.edge.name }}"
                ns: "{{ cluster.edge.ns }}"
          cilium:
            cni:
              exclusive: "{{ cluster.cni.exclusive }}"
            ui:
              enabled: "{{ cluster.cni.ui }}"

  - name: Deploy Istio, if enabled
    when: "cluster.mesh.enabled | bool == true"
    block:
    - name: Deploy Istio
      kubernetes.core.helm:
        name: istio
        create_namespace: true
        release_namespace: "{{ cluster.mesh.ns }}"
        chart_ref: "oci://{{ host.registry.name }}.{{ host.dns.zone }}:{{ host.registry.host_port | int }}/kube-eng/kube-eng-istio"
        chart_version: "{{ host.tool.helm.chart_version }}"
        binary_path: "{{ host.tool.helm.path }}"
        wait: true
        values:
          ambient: "{{ cluster.mesh.kind == 'istio-ambient' }}"
          classic_gateway: "{{ cluster.edge.kind == 'istio' }}"
          overrides_istiod:
            defaultRevision: default
            profile: "{{ (cluster.mesh.kind == 'istio-ambient') | ternary('ambient', 'default') }}"
          overrides_cni:
            profile: "{{ (cluster.mesh.kind == 'istio-ambient') | ternary('ambient', 'default') }}"
    - name: Create a service entry for the S3 service, if enabled
      when: "host.s3.enabled | bool == true"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.istio.io/v1
          kind: ServiceEntry
          metadata:
            name: service-s3
            namespace: "{{ cluster.mesh.ns }}"
            labels:
              app.kubernetes.io/name: service-s3
          spec:
            location: MESH_EXTERNAL
            resolution: DNS
            hosts:
            - "{{ host.s3.name }}.kind"
            ports:
            - name: s3-https
              number: 9000
              protocol: TLS
    - name: Create a service entry for the PG service, if enabled
      when: "host.postgresql.enabled | bool == true"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.istio.io/v1
          kind: ServiceEntry
          metadata:
            name: service-pg
            namespace: "{{ cluster.mesh.ns }}"
            labels:
              app.kubernetes.io/name: service-pg
          spec:
            location: MESH_EXTERNAL
            resolution: DNS
            hosts:
            - "{{ host.postgresql.name }}.kind"
            ports:
            - name: postgres
              number: 5432
              protocol: TCP
    - name: Create a service entry for the IDP service, if enabled
      when: "host.idp.enabled | bool == true"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.istio.io/v1
          kind: ServiceEntry
          metadata:
            name: service-idp
            namespace: "{{ cluster.mesh.ns }}"
            labels:
              app.kubernetes.io/name: service-idp
          spec:
            location: MESH_EXTERNAL
            resolution: DNS
            hosts:
            - "{{ host.idp.name }}.kind"
            ports:
            - name: idp-https
              number: 8443
              protocol: TLS

  - name: Deploy cluster PKI
    block:
    - name: Create and label the cert-manager namespace
      ansible.builtin.import_role:
        name: create_namespace
      vars:
        ns: "{{ cluster.pki.ns }}"
        mesh: "{{ cluster.mesh.kind }}"
    - name: Apply the cert-manager CRDs
      kubernetes.core.k8s:
        state: present
        apply: true
        src: "{{ preheat_path }}/cert-manager-crds.yaml"
        server_side_apply:
          field_manager: ansible
        wait: true
    - name: Create a secret from the local CA files
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          type: Opaque
          metadata:
            name: cluster-ca
            namespace: "{{ cluster.pki.ns }}"
          data:
            tls.crt: "{{ lookup('ansible.builtin.file', host.pki.ca_path) | b64encode }}"
            tls.key: "{{ lookup('ansible.builtin.file', host.pki.ca_key_path) | b64encode }}"
    - name: Declare the local CA as an issuer
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: ca-issuer
            namespace: "{{ cluster.pki.ns }}"
          spec:
            ca:
              secretName: cluster-ca
    - name: Deploy the cert-manager Helm chart
      kubernetes.core.helm:
        name: cert-manager
        create_namespace: false
        release_namespace: "{{ cluster.pki.ns }}"
        chart_ref: "oci://{{ host.registry.name }}.{{ host.dns.zone }}:{{ host.registry.host_port | int }}/kube-eng/kube-eng-cert-manager"
        chart_version: "{{ host.tool.helm.chart_version }}"
        binary_path: "{{ host.tool.helm.path }}"
        wait: true
        values:
          overrides:
            namespace: "{{ cluster.pki.ns }}"
            prometheus:
              enabled: "{{ stack.prometheus.enabled | bool }}"

  - name: Deploy Edge
    block:
    - name: Create and label the Edge namespace
      ansible.builtin.import_role:
        name: create_namespace
      vars:
        ns: "{{ cluster.edge.ns }}"
        mesh: "{{ cluster.mesh.kind }}"
    - name: Deploy the Edge Helm chart
      kubernetes.core.helm:
        name: edge
        create_namespace: false
        release_namespace: "{{ cluster.edge.ns }}"
        chart_ref: "oci://{{ host.registry.name }}.{{ host.dns.zone }}:{{ host.registry.host_port | int }}/kube-eng/kube-eng-edge"
        chart_version: "{{ host.tool.helm.chart_version }}"
        binary_path: "{{ host.tool.helm.path }}"
        wait: true
        values:
          cluster:
            name: "{{ cluster.name }}"
            edge:
              kind: "{{ cluster.edge.kind }}"
              name: "{{ cluster.edge.name }}"
          gateway:
            classname: "{{ cluster.edge.gateway_class }}"
          stack:
            prometheus:
              enabled: "{{ stack.prometheus.enabled }}"
              fqdn: "{{ stack.prometheus.hostname }}.{{ host.dns.zone }}"
            alloy:
              enabled: "{{ stack.alloy.enabled }}"
              fqdn: "{{ stack.alloy.hostname }}.{{ host.dns.zone }}"
            grafana:
              enabled: "{{ stack.grafana.enabled }}"
              fqdn: "{{ stack.grafana.hostname }}.{{ host.dns.zone }}"
            kiali:
              enabled: "{{ stack.kiali.enabled }}"
              fqdn: "{{ stack.kiali.hostname }}.{{ host.dns.zone }}"
            loki:
              enabled: "{{ stack.loki.enabled }}"
              fqdn: "{{ stack.loki.hostname }}.{{ host.dns.zone }}"

# You now need to start cloud-provider-kind as root
