---
- name: Apply the cluster configuration
  hosts: localhost
  tasks:

  # This will fail if we use a local DNS server and haven't pointed to it yet
  - name: Upload the Helm charts to the local registry
    ansible.builtin.command:
      cmd: |
        {{ host.tool.helm.path }} push 
        {{ host.tool.helm.packaged_chart_path }}/{{ item }}-{{ host.tool.helm.chart_version }}.tgz 
        oci://{{ host.registry.name }}.{{ cluster.name }}.{{ host.dns.zone }}:{{ host.registry.port | int }}/kube-eng
    loop:
    - kube-eng-alloy
    - kube-eng-cert-manager
    - kube-eng-edge
    - kube-eng-grafana
    - kube-eng-istio
    - kube-eng-jaeger
    - kube-eng-keycloak
    - kube-eng-keycloak-operator
    - kube-eng-kiali
    - kube-eng-loki
    - kube-eng-prometheus

  - name: Template the cluster configuration
    ansible.builtin.import_role:
      name: kind_configuration
    vars:
      control_plane_nodes: "{{ cluster.control_plane_nodes | int }}"
      worker_nodes: "{{ cluster.worker_nodes | int }}"
      directory: "{{ host.tool.kind.config_path }}"
      ca_file_path: "{{ cluster.pki.config_path }}/ca.pem"
      airgap_registry_name: "{{ host.registry.name }}"
      pod_subnet_cidr: "{{ cluster.pod_subnet_cidr }}"
      service_subnet_cidr: "{{ cluster.service_subnet_cidr }}"
      cni: "{{ cluster.cni.kind }}"

  - name: Create the cluster
    kind_cluster:
      name: "{{ cluster.name }}"
      config_file: "{{ host.tool.kind.config_path }}/config.yaml"
      tool_kind: "{{ host.tool.kind.path }}"
      state: present

  - name: Install Calico CNI, if enabled
    when: "cluster.cni.kind == 'calico'"
    block:
    - name: Apply the Calico Operator CRDs
      kubernetes.core.k8s:
        state: present
        apply: true
        src: "{{ preheat_path }}/calico-operator-crds.yaml"
        server_side_apply:
          field_manager: ansible
        wait: true
    - name: Apply the Calico Tigera Operator CRDs
      kubernetes.core.k8s:
        state: present
        apply: true
        src: "{{ preheat_path }}/calico-tigera-crds.yaml"
        server_side_apply:
          field_manager: ansible
        wait: true
    - name: Configure the Calico Installation
      kubernetes.core.k8s:
        state: present
        apply: true
        definition:
          apiVersion: operator.tigera.io/v1
          kind: Installation
          metadata:
            name: default
          spec:
            kubernetesProvider: Kind
            serviceCIDRs:
            - "{{ cluster.service_subnet_cidr }}"
            calicoNetwork:
              ipPools:
              - name: default-ipv4-ippool
                cidr: "{{ cluster.pod_subnet_cidr }}"
                encapsulation: VXLANCrossSubnet
                natOutgoing: Enabled
                nodeSelector: all()
                blockSize: 26
    - name: Configure the Calico API Server
      kubernetes.core.k8s:
        state: present
        apply: true
        definition:
          apiVersion: operator.tigera.io/v1
          kind: APIServer
          metadata:
            name: default
          spec: {}
    - name: Configure the Calico Goldmane flow aggregator
      kubernetes.core.k8s:
        state: present
        apply: true
        definition:
          apiVersion: operator.tigera.io/v1
          kind: Goldmane
          metadata:
            name: default
          spec: {}

    # Note: This should not run at the same time as cloud-provider-kind, as it will create
    # a conflict for the field-manager.
  - name: Apply the Gateway API CRDs
    kubernetes.core.k8s:
      state: present
      apply: true
      src: "{{ preheat_path }}/gateway-api-crds.yaml"
      server_side_apply:
        field_manager: ansible
      wait: true

  - name: Deploy Istio, if enabled
    when: "cluster.mesh.enabled == true"
    kubernetes.core.helm:
      name: istio
      create_namespace: true
      release_namespace: "{{ cluster.mesh.ns }}"
      chart_ref: "oci://{{ host.registry.name }}.{{ cluster.name }}.{{ host.dns.zone }}:{{ host.registry.port | int }}/kube-eng/kube-eng-istio"
      chart_version: "{{ host.tool.helm.chart_version }}"
      binary_path: "{{ host.tool.helm.path }}"
      wait: true
      values:
        cluster:
          mesh:
            kind: "{{ cluster.mesh.kind }}"
        istio:
          ambient: "{{ cluster.mesh.kind == 'istio-ambient' }}"
          gateway: true
        overrides_istiod:
          profile: "{{ cluster.mesh.kind == 'istio-ambient' | ternary('ambient', 'default') }}"
        overrides_cni:
          profile: "{{ cluster.mesh.kind == 'istio-ambient' | ternary('ambient', 'default') }}"

  - name: Deploy cluster PKI
    block:
    - name: Create and label the cert-manager namespace
      ansible.builtin.import_role:
        name: create_namespace
      vars:
        ns: "{{ cluster.pki.ns }}"
        mesh: "{{ cluster.mesh.kind }}"
    - name: Apply the cert-manager CRDs
      kubernetes.core.k8s:
        state: present
        apply: true
        src: "{{ preheat_path }}/cert-manager-crds.yaml"
        server_side_apply:
          field_manager: ansible
        wait: true
    - name: Create a secret from the local CA files
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          type: Opaque
          metadata:
            name: cluster-ca
            namespace: "{{ cluster.pki.ns }}"
          data:
            tls.crt: "{{ lookup('ansible.builtin.file', '{{ cluster.pki.config_path }}/ca.pem') | b64encode }}"
            tls.key: "{{ lookup('ansible.builtin.file', '{{ cluster.pki.config_path }}/ca.key') | b64encode }}"
    - name: Declare the local CA as an issuer
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: ca-issuer
            namespace: "{{ cluster.pki.ns }}"
          spec:
            ca:
              secretName: cluster-ca
    - name: Deploy the cert-manager Helm chart
      kubernetes.core.helm:
        name: cert-manager
        create_namespace: false
        release_namespace: "{{ cluster.pki.ns }}"
        chart_ref: "oci://{{ host.registry.name }}.{{ cluster.name }}.{{ host.dns.zone }}:{{ host.registry.port | int }}/kube-eng/kube-eng-cert-manager"
        chart_version: "{{ host.tool.helm.chart_version }}"
        binary_path: "{{ host.tool.helm.path }}"
        wait: true
        values:
          overrides:
            namespace: "{{ cluster.pki.ns }}"
            prometheus:
              enabled: "{{ stack.prometheus.enabled | bool }}"

# You now need to start cloud-provider-kind as root
