---
- name: Update DNS
  hosts: localhost
  tasks:

  # Attempt picking up the external IP of the Edge Gateway for 10 times, waiting 5 seconds between attempts
  - name: Collect information about the Edge Gateway
    kubernetes.core.k8s_info:
      api_version: gateway.networking.k8s.io/v1
      kind: Gateway
      name: "{{ cluster.edge.name }}"
      namespace: "{{ cluster.edge.ns }}"
    register: edge_gateway
    until: edge_gateway.resources[0].status.addresses[0].value is defined
    retries: 10
    delay: 5

  - name: Do not continue if we do not have an Edge Gateway IP address at this point
    when: edge_gateway.resources[0].status.addresses[0].value is not defined
    ansible.builtin.fail:
      msg: "Could not determine the external IP address of the Edge Gateway. Have you started cloud-provider-kind?"

  - name: Update CNI UI DNS, if enabled
    when: "cluster.cni.ui | bool == true"
    block:
    - name: Update DNS with a record for CNI
      dns_record:
        dns_ip: "{{ infra.dns.ip }}"
        dns_admin_key_name: "{{ infra.dns.admin_key_name }}"
        dns_admin_key_secret: "{{ infra.dns.admin_key_secret }}"
        dns_protocol: "{{ infra.dns.protocol }}"
        dns_zone: "{{ infra.dns.zone }}"
        dns_record: "{{ cluster.cni.hostname }}.{{ infra.dns.domain }}."
        dns_value: "{{ edge_gateway.resources[0].status.addresses[0].value }}"
        dns_ttl: "{{ infra.dns.ttl | int }}"

  - name: Update Prometheus DNS, if enabled
    when: "stack.prometheus.enabled | bool == true"
    block:
    - name: Update DNS with a record for Prometheus
      dns_record:
        dns_ip: "{{ infra.dns.ip }}"
        dns_admin_key_name: "{{ infra.dns.admin_key_name }}"
        dns_admin_key_secret: "{{ infra.dns.admin_key_secret }}"
        dns_protocol: "{{ infra.dns.protocol }}"
        dns_zone: "{{ infra.dns.zone }}"
        dns_record: "{{ stack.prometheus.hostname }}.{{ infra.dns.domain }}."
        dns_value: "{{ edge_gateway.resources[0].status.addresses[0].value }}"
        dns_ttl: "{{ infra.dns.ttl | int }}"

  - name: Update Alloy DNS, if enabled
    when: "stack.alloy.enabled | bool == true"
    block:
    - name: Update DNS with a record for Alloy
      dns_record:
        dns_ip: "{{ infra.dns.ip }}"
        dns_admin_key_name: "{{ infra.dns.admin_key_name }}"
        dns_admin_key_secret: "{{ infra.dns.admin_key_secret }}"
        dns_protocol: "{{ infra.dns.protocol }}"
        dns_zone: "{{ infra.dns.zone }}"
        dns_record: "{{ stack.alloy.hostname }}.{{ infra.dns.domain }}."
        dns_value: "{{ edge_gateway.resources[0].status.addresses[0].value }}"
        dns_ttl: "{{ infra.dns.ttl | int }}"

  - name: Update Loki DNS, if enabled
    when: "stack.loki.enabled | bool == true"
    block:
    - name: Update DNS with a record for Loki
      dns_record:
        dns_ip: "{{ infra.dns.ip }}"
        dns_admin_key_name: "{{ infra.dns.admin_key_name }}"
        dns_admin_key_secret: "{{ infra.dns.admin_key_secret }}"
        dns_protocol: "{{ infra.dns.protocol }}"
        dns_zone: "{{ infra.dns.zone }}"
        dns_record: "{{ stack.loki.hostname }}.{{ infra.dns.domain }}."
        dns_value: "{{ edge_gateway.resources[0].status.addresses[0].value }}"
        dns_ttl: "{{ infra.dns.ttl | int }}"

  - name: Update Grafana DNS, if enabled
    when: "stack.grafana.enabled | bool == true"
    block:
    - name: Update DNS with a record for Grafana
      dns_record:
        dns_ip: "{{ infra.dns.ip }}"
        dns_admin_key_name: "{{ infra.dns.admin_key_name }}"
        dns_admin_key_secret: "{{ infra.dns.admin_key_secret }}"
        dns_protocol: "{{ infra.dns.protocol }}"
        dns_zone: "{{ infra.dns.zone }}"
        dns_record: "{{ stack.grafana.hostname }}.{{ infra.dns.domain }}."
        dns_value: "{{ edge_gateway.resources[0].status.addresses[0].value }}"
        dns_ttl: "{{ infra.dns.ttl | int }}"

  - name: Update Tempo DNS, if enabled
    when: "stack.tempo.enabled | bool == true"
    block:
    - name: Update DNS with a record for Tempo
      dns_record:
        dns_ip: "{{ infra.dns.ip }}"
        dns_admin_key_name: "{{ infra.dns.admin_key_name }}"
        dns_admin_key_secret: "{{ infra.dns.admin_key_secret }}"
        dns_protocol: "{{ infra.dns.protocol }}"
        dns_zone: "{{ infra.dns.zone }}"
        dns_record: "{{ stack.tempo.hostname }}.{{ infra.dns.domain }}."
        dns_value: "{{ edge_gateway.resources[0].status.addresses[0].value }}"
        dns_ttl: "{{ infra.dns.ttl | int }}"

  - name: Update Kiali DNS, if enabled
    when: "stack.kiali.enabled | bool == true"
    block:
    - name: Update DNS with a record for Kiali
      dns_record:
        dns_ip: "{{ infra.dns.ip }}"
        dns_admin_key_name: "{{ infra.dns.admin_key_name }}"
        dns_admin_key_secret: "{{ infra.dns.admin_key_secret }}"
        dns_protocol: "{{ infra.dns.protocol }}"
        dns_zone: "{{ infra.dns.zone }}"
        dns_record: "{{ stack.kiali.hostname }}.{{ infra.dns.domain }}."
        dns_value: "{{ edge_gateway.resources[0].status.addresses[0].value }}"
        dns_ttl: "{{ infra.dns.ttl | int }}"
