---
- name: (Re-)package the Helm charts
  hosts: localhost
  tasks:

  - name: Package the Helm charts
    ansible.builtin.command:
      cmd: |
        {{ host.tool.helm.path }} package 
        --version {{ host.tool.helm.chart_version }} 
        --dependency-update 
        --destination {{ host.tool.helm.packaged_chart_path }} 
        {{ host.tool.helm.chart_path }}/{{ item }}
      creates: "{{ host.tool.helm.packaged_chart_path }}/{{ item }}-{{ host.tool.helm.chart_version }}.tgz"
    loop:
    - kube-eng-alloy
    - kube-eng-cert-manager
    - kube-eng-edge
    - kube-eng-grafana
    - kube-eng-istio
    - kube-eng-jaeger
    - kube-eng-keycloak
    - kube-eng-keycloak-operator
    - kube-eng-kiali
    - kube-eng-loki
    - kube-eng-prometheus

  - name: Upload the Helm charts to the local registry
    ansible.builtin.command:
      cmd: |
        {{ host.tool.helm.path }} push 
        {{ host.tool.helm.packaged_chart_path }}/{{ item }}-{{ host.tool.helm.chart_version }}.tgz 
        oci://{{ host.registry.name }}.{{ cluster.name }}.{{ host.dns.zone }}:{{ host.registry.port | int }}/kube-eng
    loop:
    - kube-eng-alloy
    - kube-eng-cert-manager
    - kube-eng-edge
    - kube-eng-grafana
    - kube-eng-istio
    - kube-eng-jaeger
    - kube-eng-keycloak
    - kube-eng-keycloak-operator
    - kube-eng-kiali
    - kube-eng-loki
    - kube-eng-prometheus
