---
- name: Apply the host infrastructure configuration
  hosts: localhost
  tasks:

  - name: Preheat k8s yaml files for later
    block:
    - name: Create a directory for preheated files
      ansible.builtin.file:
        path: "{{ preheat_path }}"
        state: directory
    - name: Preheat the Calico Operator CRD
      ansible.builtin.get_url:
        url: "{{ cluster.cni.calico_operator_crds }}"
        dest: "{{ preheat_path }}/calico-operator-crds.yaml"
    - name: Preheat the Calico Tigera CRD
      ansible.builtin.get_url:
        url: "{{ cluster.cni.calico_tigera_crds }}"
        dest: "{{ preheat_path }}/calico-tigera-crds.yaml"
    - name: Preheat the Kubernetes Gateway CRDs
      ansible.builtin.get_url:
        url: "{{ cluster.edge.gateway_api_crds }}"
        dest: "{{ preheat_path }}/gateway-api-crds.yaml"
    - name: Preheat the CRD for cert-manager PKI
      ansible.builtin.get_url:
        url: "{{ cluster.pki.crd }}"
        dest: "{{ preheat_path }}/cert-manager-crds.yaml"
    - name: Preheat the KeyCloak Operator CRDs
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/{{ stack.keycloak.operator_version }}/kubernetes/{{ item }}"
        dest: "{{ preheat_path }}/{{ item }}"
      loop:
      - keycloaks.k8s.keycloak.org-v1.yml
      - keycloakrealmimports.k8s.keycloak.org-v1.yml

  - name: Create public key infrastructure (PKI)
    block:
    - name: Create a directory for PKI
      ansible.builtin.file:
        path: "{{ cluster.pki.config_path }}"
        state: directory
    - name: Create a private key for the local CA
      community.crypto.openssl_privatekey:
        path: "{{ cluster.pki.config_path }}/ca.key"
        type: "{{ cluster.pki.key_type }}"
        curve: "{{ cluster.pki.key_curve }}"
        size: "{{ cluster.pki.key_size }}"
        return_content: true
        state: present
    - name: Generate a CSR for the local CA
      community.crypto.openssl_csr:
        path: "{{ cluster.pki.config_path }}/ca.csr"
        privatekey_path: "{{ cluster.pki.config_path }}/ca.key"
        common_name: "{{ cluster.name }} Local CA"
        key_usage_critical: true
        key_usage:
        - keyCertSign
        - cRLSign
        basic_constraints_critical: true
        basic_constraints:
        - "CA:TRUE"
        - "pathlen:1"
    - name: Create a self-signed local CA
      community.crypto.x509_certificate:
        path: "{{ cluster.pki.config_path }}/ca.pem"
        privatekey_path: "{{ cluster.pki.config_path }}/ca.key"
        csr_path: "{{ cluster.pki.config_path }}/ca.csr"
        provider: selfsigned
        return_content: true

  - name: Template the cloud-provider-kind configuration
    ansible.builtin.import_role:
      name: cloud_provider_kind_configuration
    vars:
      cloud_provider_kind_url: "{{ host.tool.cloud_provider_kind.url }}"
      cloud_provider_kind_dir: "{{ host.tool.cloud_provider_kind.config_path }}"

  - name: Template the cloud-provider-mdns configuration
    ansible.builtin.import_role:
      name: cloud_provider_mdns_configuration
    vars:
      tool_cloud_provider_mdns: "{{ host.tool.cloud_provider_mdns.path }}"
      directory: "{{ host.tool.cloud_provider_mdns.config_path }}"
      user: "{{ user_id }}"

  - name: Create a dedicated docker network
    community.docker.docker_network:
      name: kind

  - name: Create a local DNS server, if enabled to run locally
    when: host.dns.kind == 'local'
    block:
    - name: Create a directory for DNS
      ansible.builtin.file:
        path: "{{ host.dns.config_path }}"
        state: directory
    - name: Template the local DNS configuration
      ansible.builtin.import_role:
        name: dns_local_configuration
      vars:
        dns_local_config_path: "{{ host.dns.config_path }}"
        dns_local_forwarders: "{{ host.dns.forwarders }}"
        dns_local_zone: "{{ host.dns.zone }}"
        dns_local_update_key: "{{ host.dns.key_secret }}"
    - name: Create a volume for the DNS cache
      community.docker.docker_volume:
        name: "{{ host.dns.volume_name }}-cache"
        state: present
    - name: Create a volume for the DNS zones
      community.docker.docker_volume:
        name: "{{ host.dns.volume_name }}-zones"
        state: present
    - name: Start the local DNS server
      community.docker.docker_container:
        name: "{{ host.dns.name }}"
        image: "{{ host.dns.image }}"
        mounts:
        - source: "{{ host.dns.volume_name }}-cache"
          target: /var/cache/bind
          type: volume
        - source: "{{ host.dns.volume_name }}-zones"
          target: /var/lib/bind
          type: volume
        - source: "{{ host.dns.config_path }}/named.conf"
          target: /etc/bind/named.conf
          read_only: true
          type: bind
        - source: "{{ host.dns.config_path }}/update.key"
          target: /etc/bind/update.key
          read_only: true
          type: bind
        - source: "{{ host.dns.config_path }}/db.{{ host.dns.zone }}"
          target: /var/lib/bind/db.{{ host.dns.zone }}
          type: bind
        ports:
        - "127.0.0.1:{{ host.dns.port }}:53/udp"
        - "127.0.0.1:{{ host.dns.port }}:53/tcp"
        - "127.0.0.1:{{ host.dns.control_port }}:953/tcp"
        networks:
        - name: kind
          aliases: "{{ host.dns.name }}"
        keep_volumes: false
        restart_policy: always
        state: healthy

  - name: Create a local air-gapped registry, if enabled
    when: host.registry.enabled == true
    block:
    - name: Configure the air-gapped registry
      ansible.builtin.import_role:
        name: registry_configuration
      vars:
        directory: "{{ host.registry.config_path }}"
    - name: Create a private key for the air-gapped registry
      community.crypto.openssl_privatekey:
        path: "{{ host.registry.config_path }}/registry.key"
        type: "{{ cluster.pki.key_type }}"
        curve: "{{ cluster.pki.key_curve }}"
        size: "{{ cluster.pki.key_size }}"
        state: present
    - name: Generate a CSR for the air-gapped registry
      community.crypto.openssl_csr:
        path: "{{ host.registry.config_path }}/registry.csr"
        privatekey_path: "{{ host.registry.config_path }}/registry.key"
        common_name: "{{ host.registry.name }}.{{ cluster.name }}.{{ host.dns.zone }}"
        subject_alt_name:
        - "DNS:{{ host.registry.name }}.{{ cluster.name }}.{{ host.dns.zone }}"
        - "DNS:{{ host.registry.name }}"
        - "DNS:localhost"
        basic_constraints_critical: true
        basic_constraints:
        - "CA:FALSE"
    - name: Sign the certificate for the air-gapped registry
      community.crypto.x509_certificate:
        path: "{{ host.registry.config_path }}/registry.pem"
        csr_path: "{{ host.registry.config_path }}/registry.csr"
        ownca_path: "{{ cluster.pki.config_path }}/ca.pem"
        ownca_privatekey_path: "{{ cluster.pki.config_path }}/ca.key"
        ownca_not_after: "{{ cluster.pki.crt_validity }}"
        provider: ownca
    - name: Create a volume for the air-gapped registry
      community.docker.docker_volume:
        name: "{{ host.registry.volume_name }}"
        state: present
    - name: Start the air-gapped registry
      community.docker.docker_container:
        name: "{{ host.registry.name }}"
        image: "{{ host.registry.image }}"
        mounts:
        - source: "{{ host.registry.volume_name }}"
          target: /data
        - source: "{{ host.registry.config_path }}/config.json"
          target: /etc/zot/config.json
          read_only: true
          type: bind
        - source: "{{ host.registry.config_path }}/registry.key"
          target: /etc/zot/registry.key
          read_only: true
          type: bind
        - source: "{{ host.registry.config_path }}/registry.pem"
          target: /etc/zot/registry.pem
          read_only: true
          type: bind
        ports:
        - "127.0.0.1:{{ host.registry.port | int }}:5000"
        networks:
        - name: kind
          aliases: "{{ host.registry.name }}"
        keep_volumes: false
        restart_policy: always
        state: healthy
    - name: Update DNS with a record for the air gapped registry
      community.general.nsupdate:
        key_name: "{{ host.dns.key_name }}"
        key_secret: "{{ host.dns.key_secret }}"
        key_algorithm: "{{ host.dns.key_algorithm }}"
        server: "{{ host.dns.server }}"
        port: "{{ host.dns.port | int }}"
        protocol: "{{ host.dns.protocol }}"
        record: "{{ host.registry.name }}.{{ cluster.name }}.{{ host.dns.zone }}."
        ttl: "{{ host.dns.ttl | int }}"
        value: 127.0.0.1
        type: A
        state: present

  - name: Create a local PostgreSQL instance, if enabled
    when: host.postgresql.enabled == true
    block:
    - name: Create a volume for PostgreSQL
      community.docker.docker_volume:
        name: "{{ host.postgresql.volume_name }}"
        state: present
    - name: Start PostgreSQL
      community.docker.docker_container:
        name: "{{ host.postgresql.name }}"
        image: "{{ host.postgresql.image }}"
        ports:
        - "127.0.0.1:{{ host.postgresql.port | int }}:5432"
        mounts:
        - source: "{{ host.postgresql.volume_name }}"
          target: /var/lib/postgresql/data
        networks:
        - name: kind
          aliases: "{{ host.postgresql.name }}.{{ cluster.name }}.{{ host.dns.zone }}"
        env:
          POSTGRES_PASSWORD: "{{ admin_password }}"
          PGDATA: /var/lib/postgresql/data
        keep_volumes: false
        restart_policy: always
        state: healthy
    - name: Update DNS with a record for PostgreSQL
      community.general.nsupdate:
        key_name: "{{ host.dns.key_name }}"
        key_secret: "{{ host.dns.key_secret }}"
        key_algorithm: "{{ host.dns.key_algorithm }}"
        server: "{{ host.dns.server }}"
        port: "{{ host.dns.port | int }}"
        protocol: "{{ host.dns.protocol }}"
        record: "{{ host.postgresql.name }}.{{ cluster.name }}.{{ host.dns.zone }}."
        ttl: "{{ host.dns.ttl | int }}"
        value: 127.0.0.1
        type: A
        state: present

  - name: Create a local MinIO instance, if enabled
    when: host.minio.enabled == true
    block:
    - name: Create a volume for Minio
      community.docker.docker_volume:
        name: "{{ host.minio.volume_name }}"
        state: present
    - name: Start MinIO
      community.docker.docker_container:
        name: "{{ host.minio.name }}"
        image: "{{ host.minio.image }}"
        ports:
        - "127.0.0.1:{{ host.minio.port | int }}:9000"
        - "127.0.0.1:{{ host.minio.console_port | int }}:9001"
        mounts:
        - source: "{{ host.minio.volume_name }}"
          target: /data
        networks:
        - name: kind
          aliases: "{{ host.minio.name }}"
        env:
          MINIO_ROOT_USER: admin
          MINIO_ROOT_PASSWORD: "{{ admin_password }}"
        command: "server /data --console-address ':9001'"
        keep_volumes: false
        restart_policy: always
        state: healthy
    - name: Update DNS with a record for MinIO
      community.general.nsupdate:
        key_name: "{{ host.dns.key_name }}"
        key_secret: "{{ host.dns.key_secret }}"
        key_algorithm: "{{ host.dns.key_algorithm }}"
        server: "{{ host.dns.server }}"
        port: "{{ host.dns.port | int }}"
        protocol: "{{ host.dns.protocol }}"
        record: "{{ host.minio.name }}.{{ cluster.name }}.{{ host.dns.zone }}."
        ttl: "{{ host.dns.ttl | int }}"
        value: 127.0.0.1
        type: A
        state: present

  - name: Create a local Kafka instance, if enabled
    when: host.kafka.enabled == true
    block:
    - name: Configure the Kafka secrets directory
      ansible.builtin.file:
        path: "{{ host.kafka.config_path }}/secrets"
        state: directory
    - name: Configure the Kafka config directory
      ansible.builtin.file:
        path: "{{ host.kafka.config_path }}/config"
        state: directory
    - name: Create a volume for Kafka
      community.docker.docker_volume:
        name: "{{ host.kafka.volume_name }}"
        state: present
    - name: Start Kafka
      community.docker.docker_container:
        name: "{{ host.kafka.name }}"
        image: "{{ host.kafka.image }}"
        ports:
        - "127.0.0.1:{{ host.kafka.port | int }}:9092"
        mounts:
        - source: "{{ host.kafka.volume_name }}"
          target: /var/lib/kafka/data
        - source: "{{ host.kafka.config_path }}/config"
          target: /mnt/shared/config
          type: bind
        - source: "{{ host.kafka.config_path }}/secrets"
          target: /etc/kafka/secrets
          read_only: true
          type: bind
        networks:
        - name: kind
          aliases: "{{ host.kafka.name }}"
        keep_volumes: false
        restart_policy: always
        state: healthy
    - name: Update DNS with a record for Kafka
      community.general.nsupdate:
        key_name: "{{ host.dns.key_name }}"
        key_secret: "{{ host.dns.key_secret }}"
        key_algorithm: "{{ host.dns.key_algorithm }}"
        server: "{{ host.dns.server }}"
        port: "{{ host.dns.port | int }}"
        protocol: "{{ host.dns.protocol }}"
        record: "{{ host.kafka.name }}.{{ cluster.name }}.{{ host.dns.zone }}."
        ttl: "{{ host.dns.ttl | int }}"
        value: 127.0.0.1
        type: A
        state: present

  - name: Package the Helm charts
    ansible.builtin.command:
      cmd: |
        {{ host.tool.helm.path }} package 
        --version {{ host.tool.helm.chart_version }} 
        --dependency-update 
        --destination {{ host.tool.helm.packaged_chart_path }} 
        {{ host.tool.helm.chart_path }}/{{ item }}
      creates: "{{ host.tool.helm.packaged_chart_path }}/{{ item }}-{{ host.tool.helm.chart_version }}.tgz"
    loop:
    - kube-eng-alloy
    - kube-eng-cert-manager
    - kube-eng-edge
    - kube-eng-grafana
    - kube-eng-istio
    - kube-eng-jaeger
    - kube-eng-keycloak
    - kube-eng-keycloak-operator
    - kube-eng-kiali
    - kube-eng-loki
    - kube-eng-prometheus

#
# If you used a local DNS server, then you must now configure your host to point to 127.0.0.1:53
# You must also trust the CA that was generated for you using security add-certificates ~/.kube-eng/pki/ca.pem