#SPDX-License-Identifier: MIT-0
---
- name: Create directories for cloud-provider-mdns
  ansible.builtin.file:
    path: "{{ directory }}"
    state: directory

- name: Template the cloud-provider-mdns configuration
  ansible.builtin.template:
    src: templates/org.mrmat.kubeeng.cloudprovidermdns.plist.j2
    dest: "{{ directory }}/org.mrmat.kubeeng.cloudprovidermdns.plist"
