{{- if .Values.integration.loki.enabled }}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: datasource-loki
  labels:
    {{ include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: datasource-loki
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: loki
    type: loki
    access: proxy
    url: {{ .Values.integration.loki.url }}
    isDefault: false
{{- end }}
