{{- if .Values.integration.tempo.enabled }}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: datasource-tempo
  labels:
    {{ include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: datasource-tempo
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: tempo
    type: tempo
    access: proxy
    url: {{ .Values.integration.tempo.url }}
    isDefault: false
{{- end }}
