apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: datasource-tempo
  labels:
    {{ include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: datasource-loki
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: tempo
    type: tempo
    access: proxy
    url: http://tempo.tempo.svc.cluster.local:3200
    isDefault: true
