apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  labels:
    {{ include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: grafana-admin-secret
type: Opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: "{{ .Values.integration.adminPassword }}"
  GF_SECURITY_ADMIN_USER: "{{ .Values.integration.adminUser }}"
