apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  name: kiali-grafana-serviceaccount
  labels:
    {{ include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: kiali-grafana-serviceaccount
spec:
  name: "kiali-grafana-serviceaccount"
  instanceName: "grafana"  # Matches the exact metadata.name of a Grafana instance in the same namespace
  role: "Viewer"               # Admin, Editor, or Viewer
  isDisabled: false
  tokens:
  - name: "kiali-grafana-token"
    secretName: kiali-grafana-token   # If secretName is omitted, a name is generated prefixed with the serviceaccount and token names
    expires: 2029-12-31T14:00:00+02:00
