#
# Default values for Kube Eng :: Edge

cluster:
  name: cluster
  edge:
    kind: istio-ambient
    name: edge

gateway:
  classname: istio

stack:
  prometheus:
    enabled: false
    fqdn: prometheus.cluster.k8s
  alloy:
    enabled: false
    fqdn: alloy.cluster.k8s
  tempo:
    enabled: false
    fqdn: tempo.cluster.k8s
  grafana:
    enabled: false
    fqdn: grafana.cluster.k8s
  keycloak:
    enabled: false
    fqdn: keycloak.cluster.k8s
  kiali:
    enabled: false
    fqdn: kiali.cluster.k8s
