#
# Default values for Kube Eng :: Edge

cluster:
  name: cluster
  edge:
    kind: istio-ambient
    name: edge

gateway:
  classname: istio

stack:
  cni:
    enabled: true
    fqdn: cni.cluster.k8s
  prometheus:
    enabled: true
    fqdn: prometheus.cluster.k8s
  alloy:
    enabled: false
    fqdn: alloy.cluster.k8s
  keycloak:
    enabled: false
    fqdn: keycloak.cluster.k8s
  grafana:
    enabled: false
    fqdn: grafana.cluster.k8s
  jaeger:
    enabled: false
    fqdn: jaeger.cluster.k8s
  kiali:
    enabled: false
    fqdn: kiali.cluster.k8s
  loki:
    enabled: false
    fqdn: loki.cluster.k8s
