#
# Default values for Kube Eng :: Grafana

cluster:
  mesh: istio
  gateway_api: true
  name: cluster
  domain: local

edge:
  ns: edge
  name: edge-ingress
  kind: istio
  ingress_class: traefik

route:
  name: route-grafana
  hostname: grafana
  sectionName: grafana

#
# Dependency Chart overrides

overrides:
  global:
    imageRegistry: null
  replicas: 1
  extraLabels:
    app: grafana
    version: 8.8.2
  serviceAccount:
    create: true
    name: sa-grafana
  service:
    enabled: true
    type: ClusterIP
    appProtocol: http
  ingress:
    enabled: false
  persistence:
    type: pvc
    enabled: true
    size: 3Gi
  adminUser: admin
  adminPassword: admin
  envRenderSecret:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ""
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ""
  grafana.ini:
    analytics:
      check_for_updates: false
    server:
      root_url: http://grafana.local
    auth.basic:
      enabled: true
    auth.generic_oauth:
      enabled: true
      name: Keycloak-OAuth
      auth_url: http://keycloak.covenant.local/realms/master/protocol/openid-connect/auth
      token_url: http://kube-eng-keycloak-svc.kube-eng.svc.cluster.local/realms/master/protocol/openid-connect/token
      api_url: http://kube-eng-keycloak-svc.kube-eng.svc.cluster.local/realms/master/protocol/openid-connect/userinfo
      allow_sign_up: true
      scopes: openid email profile offline_access roles
      email_attribute_path: email
      login_attribute_path: username
      name_attribute_path: full_name
      role_attribute_path: contains(resource_access.grafana.roles.[*], "Admin") && 'Admin' || contains(resource_access.grafana.roles.[*], "Editor") && 'Editor' || 'Viewer'
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
          foldersFromFilesStructure: true
  dashboards:
    default:
      k8s-dashboard:
        gnetId: 15661
        revision: 2
        datasource: Prometheus
      coredns-dashboard:
        gnetId: 15762
        revision: 20
        datasource: Prometheus
      istio-control-plane-dashboard:
        gnetId: 7645
        revision: 255
        datasource: Prometheus
      istio-mesh-dashboard:
        gnetId: 7639
        revision: 255
        datasource: Prometheus
      istio-performance-dashboard:
        gnetId: 11829
        revision: 255
        datasource: Prometheus
      istio-service-dashboard:
        gnetId: 7636
        revision: 255
        datasource: Prometheus
      istio-wasm-dashboard:
        gnetId: 13277
        revision: 212
        datasource: Prometheus
      istio-workload-dashboard:
        gnetId: 7630
        revision: 255
        datasource: Prometheus
      istio-ztunnel-dashboard:
        gnetId: 21306
        revision: 22
        datasource: Prometheus
      keycloak-metrics-dashboard:
        gnetId: 10441
        revision: 2
        datasource: Prometheus
