apiVersion: v2
name: kube-eng-kiali
version: 0.0.0
description: A Helm chart to install Kiali
type: application
keywords:
- kube-eng
- istio
- kiali
sources:
- https://github.com/MrMatAP/kube-eng
maintainers:
- name: MrMatAP
  email: imfeldma@gmail.com
  url: https://github.com/MrMatAP
appVersion: "v2.20.0"
annotations:
  org.opencontainers.image.title: kube-eng-kiali
  org.opencontainers.image.description: A customised Helm chart wrapping Kiali in Kube-Eng clusters
  org.opencontainers.image.source: https://github.com/MrMatAP/kube-eng
  org.opencontainers.image.licenses: "MIT, Apache-2.0"
  org.opencontainers.image.authors: "MrMat <imfeldma@gmail.com>"
  org.opencontainers.image.vendor: "The MrMat Organisation"
dependencies:
- name: kiali-operator
  version: 2.27.0
  repository: https://kiali.org/helm-charts
