apiVersion: v2
name: kube-eng-kiali
version: 0.0.0
description: A Helm chart to install Kiali
type: application
keywords:
- kube-eng
- istio
- kiali
sources:
- https://github.com/MrMatAP/kube-eng
maintainers:
- name: MrMatAP
  email: imfeldma@gmail.com
  url: https://github.com/MrMatAP
appVersion: "v2.20.0"
dependencies:
- name: kiali-operator
  version: 2.23.0
  repository: https://kiali.org/helm-charts
