#
# Default values for Kube Eng :: Kiali

cluster:
  name: cluster
  edge:
    kind: traefik
    fqdn: kiali.cluster.k8s
    gateway:
      name: gateway
      ns: edge
      section: kiali

kiali-operator:
  watchNamespace: kiali
  allowAdHocNamespaces: false
  cr:
    create: false

integration:
  keycloak:
    client_id: null
    issuer_uri: null
  prometheus:
    ns: prometheus
    hostname: prometheus
    url: http://prometheus.cluster.k8s:9090
  grafana:
    ns: grafana
    fqdn: grafana.cluster.k8s
    auth:
      type: bearer
      username: null
      token: null
  jaeger:
    ns: jaeger
    fqdn: jaeger.cluster.k8s

# To authenticate to Grafana, create a service account, set type to 'bearer' and specify the token.
# alternatively, set token to 'basic' and specify username and password