#
# Default values for Kube Eng :: Kiali

cluster:
  name: cluster
  edge:
    kind: traefik
    fqdn: kiali.cluster.k8s
    gateway:
      name: edge
      ns: edge
      section: kiali

kiali-operator:
  watchNamespace: kiali
  allowAdHocNamespaces: false
  cr:
    create: false

integration:
  keycloak:
    client_id: null
    issuer_uri: null
  prometheus:
    ns: prometheus
    hostname: prometheus
    url: http://prometheus.cluster.k8s:9090
  grafana:
    external_url: https://grafana.cluster.k8s
    internal_url: http://grafana-service.grafana.svc.cluster.local:3000
    auth:
      type: bearer
      username: null
      token: null
  tempo:
    external_url: https://tempo.cluster.k8s
    internal_url: http://tempo.tempo.svc.cluster.local:3200
    collector_url: tempo.tempo.svc.cluster.local:4317

# To authenticate to Grafana, create a service account, set type to 'bearer' and specify the token.
# alternatively, set token to 'basic' and specify username and password