{{- if .Values.httproute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.httproute.name }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.AppVersion }}
    app.kubernetes.io/name: {{ .Values.httproute.name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
spec:
  hostnames:
  {{- range .Values.httproute.hostnames }}
  - {{ . | quote }}
  {{- end }}
  parentRefs:
  {{- range .Values.httproute.parents }}
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .name }}
    namespace: {{ .namespace }}
  {{- end }}
  rules:
  - backendRefs:
    - name: mrmat-prometheus-server
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
{{- end }}
