{{- if eq $.Values.edge.kind "istio" }}
---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: grafana-gateway
  labels:
    {{ include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: grafana
spec:
  # The selector matches the ingress gateway pod labels.
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.route.hostname }}.{{ .Values.cluster.name }}.{{ .Values.cluster.domain }}
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: grafana
  labels:
    {{ include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: grafana
spec:
  hosts:
  - {{ .Values.route.hostname }}.{{ .Values.cluster.name }}.{{ .Values.cluster.domain }}
  gateways:
  - grafana-gateway
  http:
  - route:
    - destination:
        host: grafana-overrides
        port:
          number: 80
        subset: main
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: grafana
  labels:
    {{ include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: grafana
spec:
  host: grafana-overrides.{{ .Release.Namespace }}.svc.cluster.local
  subsets:
  - name: main
    labels:
      app: grafana
      version: {{ .Chart.AppVersion }}
{{- end }}
