{{- if eq $.Values.cluster.edge.kind "ingress" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: https
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
    - {{ .Values.fqdn }}
    secretName: grafana-cert
  rules:
  - host: {{ .Values.fqdn }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana-overrides
            port:
              number: 80
{{- end }}