{{- if eq $.Values.cluster.edge.kind "istio-gateway-api" }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-route
  labels:
    {{ include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: grafana-route
spec:
  hostnames:
  - {{ .Values.fqdn }}
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.cluster.edge.name }}
    namespace: {{ .Values.cluster.edge.ns }}
    sectionName: {{ .Values.fqdn }}
  rules:
  - backendRefs:
    - kind: Service
      name: grafana-overrides
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
{{- end }}