{{- if eq $.Values.edge.kind "traefik" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: https
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
    - {{ .Values.route.hostname }}.{{ .Values.cluster.name }}.{{ .Values.cluster.domain }}
    secretName: grafana-cert
  rules:
  - host: {{ .Values.route.hostname }}.{{ .Values.cluster.name }}.{{ .Values.cluster.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana-overrides
            port:
              number: 80
{{- end }}