apiVersion: v2
name: kube-eng-jaeger-v2
version: 0.0.0
description: A Helm chart to install Jaeger-v2 in a kube-eng cluster
type: application
keywords:
- kube-eng
- jaegerv2
sources:
- https://github.com/MrMatAP/kube-eng
maintainers:
- name: MrMatAP
  email: imfeldma@gmail.com
  url: https://github.com/MrMatAP
appVersion: 0.0.0
