apiVersion: v2
name: kube-eng-keycloak-operator
version: 0.0.0
description: A Helm chart to install Keycloak Operator within a kube-eng cluster
type: application
keywords:
- kube-eng
- keycloak-operator
sources:
- https://github.com/MrMatAP/kube-eng
maintainers:
- name: MrMatAP
  email: imfeldma@gmail.com
  url: https://github.com/MrMatAP
appVersion: "26.2.2"
