#
# Default values for Kube Eng :: Keycloak Operator

cluster:
  name: cluster
  edge:
    kind: traefik
    fqdn: prometheus.cluster.k8s
    gateway:
      name: gateway
      ns: edge
      section: prometheus
