apiVersion: v2
name: kube-eng-alloy
version: 0.0.0
description: A Helm chart for Grafana Alloy within a kube-eng cluster
type: application
keywords:
- kube-eng
- alloy
sources:
- https://github.com/MrMatAP/kube-eng
maintainers:
- name: MrMatAP
  email: imfeldma@gmail.com
  url: https://github.com/MrMatAP
appVersion: "v1.14.0"
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/prerelease: "false"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: myapp
      image: ghcr.io/org/myapp:4.5.6
  artifacthub.io/changes: |
    - kind: added
      description: "Added metadata"
dependencies:
- name: alloy
  repository: https://grafana.github.io/helm-charts
  version: 1.6.2
