# Default values for Kube Eng :: Alloy

cluster:
  name: cluster
  edge:
    kind: traefik
    fqdn: alloy.cluster.k8s
    gateway:
      name: gateway
      ns: edge
      section: alloy

overrides:
  fullnameOverride: alloy
  alloy:
    configMap:
      create: false
      name: alloy
      key: config.alloy
  controller:
    type: 'deployment'
    replicas: 1
  ingress:
    enabled: false
  serviceAccount:
    name: sa-alloy
