# Default values for Kube Eng :: Alloy

cluster:
  name: cluster
  edge:
    kind: traefik
    fqdn: alloy.cluster.k8s
    gateway:
      name: edge
      ns: edge
      section: alloy

alloy:
  alloy:
    configMap:
      create: false
      name: alloy
      key: config.alloy
    enableReporting: false
    mounts:
      varlog: false
  controller:
    type: 'deployment'
    replicas: 1
  ingress:
    enabled: false
  serviceAccount:
    name: sa-alloy
  networkPolicy:
    enabled: false
  serviceMonitor:
    enabled: false
    additionalLabels:
      app.kubernetes.io/monitored-by: prometheus