# Argument requirements. See https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#argument-spec
---
argument_specs:
  main:
    short_description: Preheat an image into the local airgapped registry
    options:
      airgap_registry:
        description: Name of the airgapped registry accessible from the host
        type: str
        required: false
        default: "localhost:5001"
      image:
        description: The coordinates of the container image
        type: str
        required: true