# Argument requirements. See https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#argument-spec
---
argument_specs:
  main:
    short_description: Preheat an image into the local airgapped registry
    options:
      airgap_registry:
        description: Name of the airgapped registry accessible from the host
        type: str
        required: false
        default: "localhost:5001"
      registry:
        description: Remote registry of the image to preheat
        type: str
        required: true
      repository:
        description: Remote repository of the image to preheat
        type: str
        required: true
      image:
        description: Unqualified image name to preheat
        type: str
        required: true
      tag:
        description: Tag of the image to preheat
        type: str
        required: true
