#
# Default values for Kube Eng :: Edge

cluster:
  name: cluster
  edge:
    kind: ingress
    name: edge
    external_domain: k8s
    ingress:
      repository: docker.io/traefik
      tag: v3.4.4
      fqdn: edge.cluster.k8s

stack:
  prometheus:
    enabled: false
    fqdn: prometheus.cluster.k8s
  alloy:
    enabled: false
    fqdn: alloy.cluster.k8s
  keycloak:
    enabled: false
    fqdn: keycloak.cluster.k8s
  grafana:
    enabled: false
    fqdn: grafana.cluster.k8s
  jaeger:
    enabled: false
    fqdn: jaeger.cluster.k8s
  kiali:
    enabled: false
    fqdn: kiali.cluster.k8s
