#
# Default values for Kube Eng :: Edge

cluster:
  mesh: "istio"
  gateway_api: true
  name: "cluster"
  domain: "local"

edge:
  ns: edge
  name: edge-ingress

istio: false
istio_gateway_api: true
istio_gateway_api_experimental: false
ingress: false

prometheus:
  enabled: false
  hostname: prometheus
alloy:
  enabled: false
  hostname: alloy
loki:
  enabled: false
  hostname: loki
keycloak:
  enabled: false
  hostname: keycloak
grafana:
  enabled: false
  hostname: grafana
jaeger:
  enabled: false
  hostname: jaeger
kiali:
  enabled: false
  hostname: kiali