{{- if eq .Values.cluster.edge.kind "istio" }}
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: prometheus-vsvc
  labels:
    {{ include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: prometheus-vsvc
spec:
  hosts:
  - {{ .Values.fqdn }}
  gateways:
  - {{ .Values.cluster.edge.ns }}/prometheus-gw
  - mesh
  http:
  - route:
    - destination:
        host: prometheus.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 80
        subset: main
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: prometheus-dst
  labels:
    {{ include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: prometheus-dst
spec:
  host: prometheus.{{ .Release.Namespace }}.svc.cluster.local
  subsets:
  - name: main
    labels:
      app: prometheus
      version: {{ .Chart.AppVersion }}
{{- end }}
