apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.route.name }}
  labels:
    app: {{ .Release.Name }}
    version: {{ .Chart.AppVersion }}
    app.kubernetes.io/name: {{ .Values.route.name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  hostnames:
  - {{ .Values.route.hostname }}
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.route.parent }}
    namespace: {{ .Values.route.parent_ns }}
  rules:
  - backendRefs:
    - kind: Service
      name: "{{ .Release.Name }}-server"
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
