#
# Default values for Kube Eng :: Prometheus

cluster:
  name: cluster
  edge:
    kind: istio-gateway-api
    fqdn: prometheus.cluster.k8s
    gateway:
      name: edge-gateway
      ns: edge
      section: prometheus
#
# Dependency Chart overrides

prometheus:
  fullnameOverride: prometheus
  alertmanager:
    enabled: false
    ingress:
      enabled: false
  grafana:
    enabled: false
    ingress:
      enabled: false
  prometheus:
    enabled: true
    ingress:
      enabled: false
    serviceMonitor:
      additionalLabels:
        app.kubernetes.io/monitored-by: prometheus
    prometheusSpec:
      ruleSelector:
        matchLabels:
          app.kubernetes.io/monitored-by: prometheus
      serviceMonitorSelector:
        matchLabels:
          app.kubernetes.io/monitored-by: prometheus
      podMonitorSelector:
        matchLabels:
          app.kubernetes.io/monitored-by: prometheus
      probeSelector:
        matchLabels:
          app.kubernetes.io/monitored-by: prometheus
      scrapeConfigSelector:
        matchLabels:
          app.kubernetes.io/monitored-by: prometheus
  kubeApiServer:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        app.kubernetes.io/monitored-by: prometheus
  kubelet:
    enabled: true
    serviceMonitor:
      https: true
      insecureSkipVerify: true
      cAdvisor: true
      probes: true
      additionalLabels:
        app.kubernetes.io/monitored-by: prometheus
  kubeControllerManager:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        app.kubernetes.io/monitored-by: prometheus
  coreDns:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        app.kubernetes.io/monitored-by: prometheus
  kubeEtcd:
    enabled: true
    service:
      port: 2381
      targetPort: 2381
    serviceMonitor:
      enabled: true
      scheme: http
      insecureSkipVerify: true
      additionalLabels:
        app.kubernetes.io/monitored-by: prometheus
  kubeScheduler:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        app.kubernetes.io/monitored-by: prometheus
  kubeProxy:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        app.kubernetes.io/monitored-by: prometheus
  kube-state-metrics:
    releaseLabel: true
    networkPolicy:
      enabled: false
      flavor: cilium
    selfMonitor:
      enabled: true
    prometheus:
      monitor:
        enabled: true
        additionalLabels:
          app.kubernetes.io/monitored-by: prometheus
  prometheus-node-exporter:
    networkPolicy:
      enabled: false
    prometheus:
      monitor:
        enabled: true
        additionalLabels:
          app.kubernetes.io/monitored-by: prometheus
