# Argument requirements. See https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#argument-spec
---
argument_specs:
  main:
    short_description: Template the cloud-provider-kind configuration
    options:
      cloud_provider_kind_url:
        description: URL from where to obtain cloud-provider-kind
        type: str
        required: false
        default: https://github.com/kubernetes-sigs/cloud-provider-kind/releases/download/v0.6.0/cloud-provider-kind_0.6.0_darwin_arm64.tar.gz
      cloud_provider_kind_dir:
        description: Path to the directory in which cloud-provider-kind operates
        type: str
        required: true
