#SPDX-License-Identifier: MIT-0
---
- name: Check whether we have the image in the air gapped registry
  ansible.builtin.uri:
    url: "http://{{ airgap_registry }}/v2/{{ repository }}/{{ image }}/manifests/{{ tag }}"
    method: HEAD
    headers:
      Accept: application/vnd.oci.image.index.v1+json,application/vnd.oci.image.manifest.v1+json
    status_code: [200, 404]
  register: image_status

- name: Transfer the image
  when: image_status.status != 200
  block:
  - name: Pull the image into docker
    community.docker.docker_image_pull:
      name: "{{ registry }}/{{ repository }}/{{ image }}:{{ tag }}"

  - name: Re-tag the image to the air gapped repository
    community.docker.docker_image_tag:
      name: "{{ registry }}/{{ repository }}/{{ image }}:{{ tag }}"
      repository:
      - "{{ airgap_registry }}/{{ repository }}/{{ image }}:{{ tag }}"

  - name: Push the image into the air gapped repository
    community.docker.docker_image_push:
      name: "{{ airgap_registry }}/{{ repository }}/{{ image }}"
      tag: "{{ tag }}"

  - name: Remove the duplicate images from the docker registry
    community.docker.docker_image_remove:
      name: "{{ image }}"
    loop:
    - "{{ registry }}/{{ repository }}/{{ image }}:{{ tag }}"
    - "{{ airgap_registry }}/{{ repository }}/{{ image }}:{{ tag }}"
    loop_control:
      loop_var: image
