{{- if eq $.Values.cluster.edge.kind "istio" }}
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: kiali-vsvc
  labels:
    {{ include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: kiali-vsvc
spec:
  hosts:
  - {{ .Values.fqdn }}
  gateways:
  - {{ .Values.cluster.edge.ns }}/kiali-gw
  - mesh
  http:
  - route:
    - destination:
        host: kiali.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 20001
        subset: main
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: kiali-dst
  labels:
    {{ include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: kiali-dst
spec:
  host: kiali.{{ .Release.Namespace }}.svc.cluster.local
  subsets:
  - name: main
    labels:
      app: kiali
      version: {{ .Chart.AppVersion }}
{{- end }}
