apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{ include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: sm-cert-manager
    app.kubernetes.io/monitored-by: prometheus
  name: sm-cert-manager
spec:
  jobLabel: app.kubernetes.io/component
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: cert-manager
  endpoints:
  - honorLabels: false
    interval: 10s
    scheme: http
    port: tcp-prometheus-servicemonitor
    path: /metrics
    relabelings:
    - action: replace
      replacement: ${1}
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: node
