{{- if .Values.cluster.gateway_api }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.route.name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.route.name }}
spec:
  hostnames:
  - {{ .Values.route.hostname }}.{{ .Values.cluster.name }}.{{ .Values.cluster.domain }}
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.cluster.edge }}
    namespace: {{ .Values.cluster.edge_ns }}
    sectionName: alloy
  rules:
  - backendRefs:
    - kind: Service
      name: {{ .Values.overrides.fullnameOverride }}
      port: 12345
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
{{- end }}
