---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-operator
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: keycloak-operator
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: keycloak-operator
  type: ClusterIP
