{{- if eq .Values.cluster.edge.kind "ingress" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
spec:
  tls:
  - hosts:
    - {{ .Values.fqdn }}
    secretName: loki-cert
  rules:
  - host: {{ .Values.fqdn }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: loki-gateway
            port:
              number: 80
{{- end }}