# Default values for Kube Eng :: Loki

cluster:
  name: cluster
  edge:
    kind: traefik
    fqdn: loki.cluster.k8s
    gateway:
      name: gateway
      ns: edge
      section: loki

loki:
  deploymentMode: SingleBinary
  singleBinary:
    replicas: 1
    persistence:
      enabled: true
      size: 3Gi
  loki:
    auth_enabled: false
    commonConfig:
      path_prefix: /var/loki
      replication_factor: 1
    storage:
      bucketNames:
        chunks: loki-chunks
        ruler: loki-ruler
        admin: loki-admin
      type: s3
      s3:
        endpoint: https://s3:9000
        s3ForcePathStyle: true
        accessKeyId: null
        secretAccessKey: null
        signatureVersion: v4
        http_config:
          insecure_skip_verify: true
    schemaConfig:
      configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
    pattern_ingester:
      enabled: true
    limits_config:
      allow_structured_metadata: true
      volume_enabled: true
    ruler:
      enable_api: true
    minio:
      enabled: false
    storage_config:
      tsdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/index_cache
        cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
    schema_config:
      configs:
      - from: 2020-07-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: index_
          period: 24h
  memberlist:
    service:
      publishNotReadyAddresses: true
  gateway:
    enabled: false
  enterprise:
    enabled: false
  chunksCache:
    resources:
      limits:
        memory: 4Gi
      requests:
        memory: 4Gi
  # Simple Scalable Mode
  write:
    replicas: 0
  read:
    replicas: 0
  backend:
    replicas: 0

  # Microservice Mode
  ingester:
    replicas: 0
  distributor:
    replicas: 0
  querier:
    replicas: 0
  queryFrontend:
    replicas: 0
  queryScheduler:
    replicas: 0
  indexGateway:
    replicas: 0
  compactor:
    replicas: 0
  bloomGateway:
    replicas: 0
  bloomPlanner:
    replicas: 0
  bloomBuilder:
    replicas: 0
  patternIngester:
    replicas: 0
  ruler:
    enabled: false
  overridesExporter:
    enabled: false
  minio:
    enabled: false
