#
# Default values for Kube Eng :: Prometheus

cluster:
  mesh: istio
  gateway_api: true
  name: cluster
  domain: local

edge:
  ns: edge
  name: edge-ingress
  kind: istio

route:
  name: route-prometheus
  hostname: prometheus
  sectionName: prometheus

#
# Dependency Chart overrides

overrides:
  serviceAccounts:
    server:
      create: true
      name: sa-prometheus
  configmapReload:
    prometheus:
      image:
        repository: quay.io/prometheus-operator/prometheus-config-reloader
  server:
    releaseNamespace: false
    image:
      repository: quay.io/prometheus/prometheus
    extraFlags:
    - web.enable-lifecycle
    - web.enable-admin-api
    fullnameOverride: prometheus
    ingress:
      enabled: false
    persistentVolume:
      enabled: true
      size: 3Gi
    service:
      enabled: true
      type: ClusterIP
  alertmanager:
    enabled: false
  kube-state-metrics:
    enabled: true
    global:
      imageRegistry: ""
  prometheus-node-exporter:
    fullnameOverride: prometheus-node-exporter
    enabled: true
    global:
      imageRegistry: ""
  prometheus-pushgateway:
    enabled: false
