apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: {{ .Values.route.name }}
  labels:
    app: {{ .Release.Name }}
    version: {{ .Chart.AppVersion }}
    app.kubernetes.io/name: {{ .Values.route.name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  parentRefs:
  {{- range .Values.route.parents }}
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .name }}
    namespace: {{ .namespace }}
    port: 5432
  {{- end }}
  rules:
  - backendRefs:
    - kind: Service
      name: {{ .Values.svc.name }}
      port: {{ .Values.svc.port }}
      weight: 1
