#
# Default values for Kube Eng :: Jaeger

cluster:
  control_plane_nodes: 1
  worker_nodes: 3
  mesh: "istio"
  istio_profile: "istio-experimental"
  gateway_api: true
  edge_ns: edge
  edge: edge-ingress
  name: "cluster"
  domain: "local"

route:
  name: route-jaeger
  hostname: jaeger
  sectionName: jaeger
