#
# Default values for Kube Eng :: Jaeger

cluster:
  mesh: "istio"
  istio_profile: "istio-experimental"
  gateway_api: true
  name: "cluster"
  domain: "local"

edge:
  ns: edge
  name: edge-ingress

route:
  name: route-jaeger
  hostname: jaeger
  sectionName: jaeger

jaeger:
  image: jaegertracing/jaeger:latest