#
# Default values for Kube Eng :: Keycloak

cluster:
  control_plane_nodes: 1
  worker_nodes: 3
  mesh: "istio"
  istio_profile: "istio-experimental"
  gateway_api: true
  edge_ns: edge
  edge: edge-ingress
  name: "cluster"
  domain: "local"

route:
  name: route-keycloak
  hostname: keycloak
  sectionName: keycloak

keycloak:
  instances: 1
  db: postgres
  db_user: keycloak
  db_password: admin
  db_host: kube-eng-postgres-svc.kube-eng.svc.cluster.local
  db_database: keycloak
  port: 8080
  managementPort: 9000
  admin_user: admin
  admin_password: admin
