#
# Default values for Kube Eng :: Keycloak

cluster:
  mesh: istio
  gateway_api: true
  name: cluster
  domain: local

edge:
  ns: edge
  name: edge-ingress
  kind: istio
  ingress_class: traefik

route:
  name: route-keycloak
  hostname: keycloak
  sectionName: keycloak

keycloak:
  instances: 1
  db: postgres
  db_user: keycloak
  db_password: admin
  db_host: kube-eng-postgres-svc.kube-eng.svc.cluster.local
  db_database: keycloak
  port: 8080
  managementPort: 9000
  admin_user: admin
  admin_password: admin
