{{- if eq $.Values.cluster.edge.kind "istio" }}
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: jaeger-vsvc
  labels:
    {{ include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: jaeger-vsvc
spec:
  hosts:
  - {{ .Values.fqdn }}
  gateways:
  - {{ .Values.cluster.edge.ns }}/jaeger-gw
  - mesh
  http:
  - route:
    - destination:
        host: jaeger-query.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 16686
        subset: main
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: jaeger-dst
  labels:
    {{ include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: jaeger-dst
spec:
  host: jaeger-query.{{ .Release.Namespace }}.svc.cluster.local
  subsets:
  - name: main
    labels:
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/instance: jaeger
{{- end }}
