---
- name: Create a cluster
  hosts: localhost
  tasks:
  - name: Template the cluster configuration
    ansible.builtin.import_role:
      name: mrmat.kube_eng.kind_configuration
    vars:
      control_plane_nodes: "{{ cluster.control_plane_nodes | int }}"
      worker_nodes: "{{ cluster.worker_nodes | int }}"
      config_file: "{{ dist_dir }}/kind-config.yaml"
      airgap_registry_name: "{{ host.registry.name }}"

  - name: Create the cluster
    mrmat.kube_eng.kind_cluster:
      name: "{{ cluster_name }}"
      config_file: "{{ dist_dir }}/kind-config.yaml"
      tool_kind: "{{ host.tools.kind }}"
      state: present

  - name: Install Istio
    when: "cluster.mesh == 'istio'"
    mrmat.kube_eng.istio:
      profile: "{{ cluster.istio_profile | default('minimal') }}"
      tool_kubectl: "{{ host.tools.kubectl }}"
      tool_istioctl: "{{ host.tools.istioctl }}"
      state: present

  - name: Install Gateway API
    when: "cluster.gateway_api | bool == true"
    kubernetes.core.k8s:
      src: https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.1/standard-install.yaml
      state: present

  - name: Install Gateway API (Experimental)
    when: "cluster.gateway_api_experimental | bool == true"
    kubernetes.core.k8s:
      src: https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.1/experimental-install.yaml
      state: present
