---
- name: Create a cluster
  hosts: localhost
  tasks:
  - name: Template the cluster configuration
    ansible.builtin.import_role:
      name: mrmat.kube_eng.kind_configuration
    vars:
      control_plane_nodes: "{{ cluster.control_plane_nodes | int }}"
      worker_nodes: "{{ cluster.worker_nodes | int }}"
      directory: "{{ dist_dir }}/kind"
      ca_file_path: "{{ pki_dir }}/ca.pem"
      airgap_registry_name: "{{ host.registry.name }}"

  - name: Create the cluster
    mrmat.kube_eng.kind_cluster:
      name: "{{ cluster_name }}"
      config_file: "{{ dist_dir }}/kind/config.yaml"
      tool_kind: "{{ host_tool_kind }}"
      state: present

  - name: Install Istio
    when: "cluster.mesh == 'istio'"
    mrmat.kube_eng.istio:
      profile: "{{ cluster.istio_profile | default('minimal') }}"
      tool_kubectl: "{{ host_tool_kubectl }}"
      tool_istioctl: "{{ host_tool_istioctl }}"
      hub: "{{ host.registry.name }}:5000/istio"
      state: present

  - name: Deploy the Gateway API CRD
    when: "stack.gateway_api.enabled | bool == true"
    kubernetes.core.k8s:
      state: present
      apply: true
      src: "{{ dist_dir }}/preheat/gateway-api-crds.yaml"

  - name: Deploy the experimental Gateway API CRD
    when: "stack.gateway_api.experimental | bool == true"
    kubernetes.core.k8s:
      state: present
      apply: true
      src: "{{ dist_dir }}/preheat/experimental-gateway-api-crds.yaml"
