---
- name: Preheat container images into the airgap registry
  hosts: localhost
  tasks:
    - name: Preheat the Prometheus image(s)
      ansible.builtin.include_role:
        name: mrmat.kube_eng.preheat_image
      vars:
        airgap_registry: "localhost:{{ host.registry.port }}"
        registry: "{{ item.registry }}"
        repository: "{{ item.repository }}"
        image: "{{ item.image }}"
        tag: "{{ item.tag }}"
      loop: "{{ stack.prometheus.preheat_images }}"

    - name: Preheat the Postgres image(s)
      ansible.builtin.include_role:
        name: mrmat.kube_eng.preheat_image
      vars:
        airgap_registry: "localhost:{{ host.registry.port }}"
        registry: "{{ item.registry }}"
        repository: "{{ item.repository }}"
        image: "{{ item.image }}"
        tag: "{{ item.tag }}"
      loop: "{{ stack.postgres.preheat_images }}"

    - name: Preheat the Keycloak image(s)
      ansible.builtin.include_role:
        name: mrmat.kube_eng.preheat_image
      vars:
        airgap_registry: "localhost:{{ host.registry.port }}"
        registry: "{{ item.registry }}"
        repository: "{{ item.repository }}"
        image: "{{ item.image }}"
        tag: "{{ item.tag }}"
      loop: "{{ stack.keycloak.preheat_images }}"

    - name: Preheat the Grafana image(s)
      ansible.builtin.include_role:
        name: mrmat.kube_eng.preheat_image
      vars:
        airgap_registry: "localhost:{{ host.registry.port }}"
        registry: "{{ item.registry }}"
        repository: "{{ item.repository }}"
        image: "{{ item.image }}"
        tag: "{{ item.tag }}"
      loop: "{{ stack.grafana.preheat_images }}"

    - name: Preheat the Jaeger image(s)
      ansible.builtin.include_role:
        name: mrmat.kube_eng.preheat_image
      vars:
        airgap_registry: "localhost:{{ host.registry.port }}"
        registry: "{{ item.registry }}"
        repository: "{{ item.repository }}"
        image: "{{ item.image }}"
        tag: "{{ item.tag }}"
      loop: "{{ stack.jaeger.preheat_images }}"

    - name: Preheat the Kiali image(s)
      ansible.builtin.include_role:
        name: mrmat.kube_eng.preheat_image
      vars:
        airgap_registry: "localhost:{{ host.registry.port }}"
        registry: "{{ item.registry }}"
        repository: "{{ item.repository }}"
        image: "{{ item.image }}"
        tag: "{{ item.tag }}"
      loop: "{{ stack.kiali.preheat_images }}"
