---
- name: Preheat container images into the airgap registry
  hosts: localhost
  tasks:
    - name: Preheat the image(s)
      ansible.builtin.include_role:
        name: mrmat.kube_eng.preheat_image
      vars:
        airgap_registry: "localhost:{{ host.registry.port }}"
        registry: "{{ item.registry }}"
        repository: "{{ item.repository }}"
        image: "{{ item.image }}"
        tag: "{{ item.tag }}"
      loop: "{{ preheat }}"
