---
- name: Create and configure the host infrastructure
  hosts: localhost
  tasks:
  - name: Preheat the container image(s)
    ansible.builtin.include_role:
      name: mrmat.kube_eng.preheat_image
    vars:
      image: "{{ item.image }}"
      airgap_registry: "localhost:{{ host.registry.port }}"
    loop: "{{ preheat }}"

  # TODO: coredns wants to be read from another place
  - name: Bug - Make the coredns image available at the root of the airgap
    community.docker.docker_image_pull:
      name:  "localhost:{{ host.registry.port }}/coredns/coredns:v1.11.3"
  - name: Bug - Re-tag the coredns image
    community.docker.docker_image_tag:
      name: "localhost:{{ host.registry.port }}/coredns/coredns:v1.11.3"
      repository:
      - "localhost:{{ host.registry.port }}/coredns:v1.11.3"
  - name: Bug - Push the image into the air gapped repository
    community.docker.docker_image_push:
      name: "localhost:{{ host.registry.port }}/coredns"
      tag: v1.11.3
