apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    {{ include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: pm-istio-waypoint
    app.kubernetes.io/monitored-by: prometheus
  name: pm-istio-waypoint
spec:
  jobLabel: gateway.networking.k8s.io/gateway-class-name
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      gateway.networking.k8s.io/gateway-class-name: istio-waypoint
  podMetricsEndpoints:
  - honorLabels: false
    interval: 10s
    scheme: http
    port: metrics
    path: /stats/prometheus
    relabelings:
    - action: replace
      replacement: ${1}
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: node
