#
# Default values for Kube Eng :: Grafana

cluster:
  name: cluster
  edge:
    kind: istio-gateway-api
    fqdn: grafana.cluster.k8s
    gateway:
      name: edge-gateway
      ns: edge
      section: grafana

integration:
  adminUser: ~
  adminPassword: ~
  rootUrl: http://grafana.local
  oauth:
    clientId: ~
    clientSecret: ~
    authUrl: http://keycloak.cluster.k8s/realms/master/protocol/openid-connect/auth
    tokenUrl: http://keycloak.cluster.k8s/realms/master/protocol/openid-connect/token
    apiUrl: http://keycloak.cluster.k8s/realms/master/protocol/openid-connect/userinfo
  prometheus:
    url: http://prometheus.prometheus.svc.cluster.local
    isDefault: true


operator:
  replicas: 1
  clusterDomain: cluster.local
  isOpenShift: false
  serviceMonitor:
    enabled: true
    additionalLabels:
      app.kubernetes.io/monitored-by: prometheus
  dashboard:
    enabled: true

#  dashboards:
#    default:
#      k8s-dashboard:
#        gnetId: 15661
#        revision: 2
#        datasource: Prometheus
#      coredns-dashboard:
#        gnetId: 15762
#        revision: 20
#        datasource: Prometheus
#      istio-control-plane-dashboard:
#        gnetId: 7645
#        revision: 255
#        datasource: Prometheus
#      istio-mesh-dashboard:
#        gnetId: 7639
#        revision: 255
#        datasource: Prometheus
#      istio-performance-dashboard:
#        gnetId: 11829
#        revision: 255
#        datasource: Prometheus
#      istio-service-dashboard:
#        gnetId: 7636
#        revision: 255
#        datasource: Prometheus
#      istio-wasm-dashboard:
#        gnetId: 13277
#        revision: 212
#        datasource: Prometheus
#      istio-workload-dashboard:
#        gnetId: 7630
#        revision: 255
#        datasource: Prometheus
#      istio-ztunnel-dashboard:
#        gnetId: 21306
#        revision: 22
#        datasource: Prometheus
#      keycloak-metrics-dashboard:
#        gnetId: 10441
#        revision: 2
#        datasource: Prometheus
