# Edge for Istio with the Gateway API
{{- if eq $.Values.edge.kind "istio-gateway-api" }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: edge-ingress
  labels:
    {{ include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: edge-ingress
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
 {{- if .Values.prometheus.enabled }}
  - name: prometheus
    hostname: {{ .Values.prometheus.hostname }}.{{ .Values.cluster.name }}.{{ .Values.cluster.domain }}
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: prometheus-cert
        kind: Secret
  {{- end }}
  {{- if .Values.alloy.enabled }}
  - name: alloy
    hostname: {{ .Values.alloy.hostname }}.{{ .Values.cluster.name }}.{{ .Values.cluster.domain }}
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: alloy-cert
        kind: Secret
  {{- end }}
  {{- if .Values.keycloak.enabled }}
  - name: keycloak
    hostname: {{ .Values.keycloak.hostname }}.{{ .Values.cluster.name }}.{{ .Values.cluster.domain }}
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: keycloak-cert
        kind: Secret
  {{- end }}
  {{- if .Values.grafana.enabled }}
  - name: grafana
    hostname: {{ .Values.grafana.hostname }}.{{ .Values.cluster.name }}.{{ .Values.cluster.domain }}
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: grafana-cert
        kind: Secret
  {{- end }}
  {{- if .Values.jaeger.enabled }}
  - name: jaeger
    hostname: {{ .Values.jaeger.hostname }}.{{ .Values.cluster.name }}.{{ .Values.cluster.domain }}
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: jaeger-cert
        kind: Secret
  {{- end }}
  {{- if .Values.kiali.enabled }}
  - name: kiali
    hostname: {{ .Values.kiali.hostname }}.{{ .Values.cluster.name }}.{{ .Values.cluster.domain }}
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: kiali-cert
        kind: Secret
  {{- end }}
{{- end }}
