{{- if eq $.Values.edge.kind "istio" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-ingress
  labels:
    {{ include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: edge-ingress
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: edge-ingress
  template:
    metadata:
      annotations:
        # Select the gateway injection template (rather than the default sidecar template)
        inject.istio.io/templates: gateway
      labels:
        # Set a unique label for the gateway. This is required to ensure Gateways can select this workload
        istio: ingressgateway
        app.kubernetes.io/name: edge-ingress
    spec:
      # Allow binding to all ports (such as 80 and 443)
      securityContext:
        sysctls:
        - name: net.ipv4.ip_unprivileged_port_start
          value: "0"
      containers:
      - name: istio-proxy
        image: auto # The image will automatically update each time the pod starts.
        # Drop all privileges, allowing to run as non-root
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsUser: 1337
          runAsGroup: 1337
---
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  labels:
    {{ include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: edge-ingress
spec:
  type: LoadBalancer
  selector:
    istio: ingressgateway
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
---
# Set up roles to allow reading credentials for TLS
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istio-ingressgateway-sds
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: edge-ingress
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-ingressgateway-sds
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: edge-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-ingressgateway-sds
subjects:
- kind: ServiceAccount
  name: default
{{- end }}
