#
# Default values for Kube Eng :: PostgreSQL

pvc:
  name: kube-eng-postgres-pvc
  storageClass: standard
  size: 5Gi

sa:
  name: kube-eng-postgres-sa

pod:
  name: kube-eng-postgres
  replicas: 1
  repository: postgres
  imagePullPolicy: IfNotPresent
  port: 5432
  admin_user: postgres
  admin_password: admin

svc:
  name: kube-eng-postgres-svc
  port: 5432

route:
  name: kube-eng-postgres-route
  hostname: ke-postgres.local
  parents:
  - name: istio-ingress
    namespace: edge