apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  annotations:
    ansible.sdk.operatorframework.io/verbosity: "1"
spec:
  service_type: ClusterIP
  external_services:
    istio:
      root_namespace: istio-system
    prometheus:
      url: http://mrmat-prometheus-server.prometheus.svc.cluster.local
    grafana:
      enabled: true
      internal_url: http://mrmat-grafana.grafana.svc.cluster.local/
      external_url: http://mrmat-grafana.local
      auth:
        token: ""
      dashboards:
      - name: 'Istio Mesh Dashboard'
      - name: 'Istio Control Plane Dashboard'
      - name: 'Istio Performance Dashboard'
  auth:
    strategy: anonymous
#    openid:
#      client_id: mrmat-kiali
#      issuer-uri: http://mrmat-keycloak.local/realms/master
#      disable-rbac: true
#      scopes: ["openid", "profile", "email"]
#      username_claim: "sub"
  kiali_feature_flags:
    disabled_features: []
    istio_annotation_action: true
    istio_injection_action: true
    istio_upgrade_action: false
    ui_defaults:
      graph:
        find_options:
        - description: "Find: slow edges (> 1s)"
          expression: "rt > 1000"
        - description: "Find: unhealthy nodes"
          expression: "! healthy"
        - description: "Find: unknown nodes"
          expression: "name = unknown"
        hide_options:
        - description: "Hide: healthy nodes"
          expression: "healthy"
        - description: "Hide: unknown nodes"
          expression: "name = unknown"
        settings:
          animation: "point"
        traffic:
          ambient: "total"
          grpc: "requests"
          http: "requests"
          tcp: "sent"
      i18n:
        language: "en"
        show_selector: false
      list:
        include_health: true
        include_istio_resources: true
        include_validations: true
        show_include_toggles: false
      metrics_per_refresh: "1m"
      # default: metrics_inbound is undefined
      metrics_inbound:
        aggregations:
        - display_name: "Istio Network"
          label: "topology_istio_io_network"
        - display_name: "Istio Revision"
          label: "istio_io_rev"
      # default: metrics_outbound is undefined
      metrics_outbound:
        aggregations:
        - display_name: "Istio Network"
          label: "topology_istio_io_network"
        - display_name: "Istio Revision"
          label: "istio_io_rev"
      # default: namespaces is an empty list
      namespaces: ["istio-system"]
      refresh_interval: "1m"
    validations:
      ignore: ["KIA1301"]
      skip_wildcard_gateway_hosts: false
  # default: custom_dashboards is an empty list
  custom_dashboards:
  - name: "envoy"
