# Default values for Kube Eng :: Alloy

cluster:
  control_plane_nodes: 1
  worker_nodes: 3
  mesh: "istio"
  istio_profile: "istio-experimental"
  gateway_api: true
  edge_ns: edge
  edge: edge-ingress
  name: "cluster"
  domain: "local"

overrides:
  image:
    repository: quay.io/minio/operator
  operator:
    replicaCount: 1
