apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.route.name }}
  labels:
    app: {{ .Release.Name }}
    version: {{ .Chart.AppVersion }}
    app.kubernetes.io/name: {{ .Values.route.name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  hostnames:
  - {{ .Values.route.hostname }}
  parentRefs:
  {{- range .Values.route.parents }}
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .name }}
    namespace: {{ .namespace }}
    sectionName: keycloak
  {{- end }}
  rules:
  - backendRefs:
    - kind: Service
      name: {{ .Values.svc.name }}
      port: {{ .Values.svc.port }}
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
