apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  labels:
    {{ include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: keycloak-db-secret
stringData:
  username: {{ .Values.keycloak.db_user | quote }}
  password: {{ .Values.keycloak.db_password | quote }}
