apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  labels:
    {{ include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: keycloak-admin-secret
stringData:
  username: {{ .Values.keycloak.admin_user | quote }}
  password: {{ .Values.keycloak.admin_password | quote }}
