{{- if eq $.Values.edge.kind "istio-gateway-api" }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.route.name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.route.name }}
spec:
  hostnames:
  - {{ .Values.route.hostname }}.{{ .Values.cluster.name }}.{{ .Values.cluster.domain }}
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.edge.name }}
    namespace: {{ .Values.edge.ns }}
    sectionName: {{ .Values.route.sectionName }}
  rules:
  - backendRefs:
    - kind: Service
      name: keycloak-service
      port: {{ .Values.keycloak.port }}
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
{{- end }}