apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc.name }}
  labels:
    app: {{ .Release.Name }}
    version: {{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Values.svc.name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Values.pod.name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
  ports:
  - name: http
    port: {{ .Values.svc.port }}
    protocol: TCP
    targetPort: {{ .Values.pod.port }}
  - name: management
    port: {{ .Values.svc.managementPort }}
    protocol: TCP
    targetPort: {{ .Values.pod.managementPort }}
