# Default values for mrmat-grafana

#
# Traffic Routing

httproute:
  enabled: true
  name: mrmat-grafana-httproute
  hostnames:
  - mrmat-grafana.local
  parents:
  - name: istio-ingress
    namespace: edge

#
# Dependency Chart overrides

grafana:
  extraLabels:
    app: grafana
    version: 8.8.2
  podLabels:
    sidecar.istio.io/inject: "true"
  serviceAccount:
    create: true
    name: mrmat-grafana-svc
    labels:
      app.kubernetes.io/name: mrmat-grafana-svc
      app.kubernetes.io/part-of: mrmat-grafana
  service:
    enabled: true
    type: ClusterIP
    appProtocol: http
    labels:
      app.kubernetes.io/part-of: mrmat-grafana
  ingress:
    enabled: false
  persistence:
    type: pvc
    enabled: true
    size: 3Gi
  adminUser: admin
  envRenderSecret:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ""
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ""
  grafana.ini:
    server:
      root_url: http://mrmat-grafana.local
    auth.basic:
      enabled: false
    auth:
      oauth_auto_login: true
      disable_login_form: true
    auth.generic_oauth:
      enabled: true
      name: Keycloak-OAuth
      allow_sign_up: true
      scopes: openid email profile offline_access roles
      email_attribute_path: email
      login_attribute_path: username
      name_attribute_path: full_name
      auth_url: http://mrmat-keycloak.local/realms/master/protocol/openid-connect/auth
      token_url: http://mrmat-keycloak-svc.keycloak.svc.cluster.local/realms/master/protocol/openid-connect/token
      api_url: http://mrmat-keycloak-svc.keycloak.svc.cluster.local/realms/master/protocol/openid-connect/userinfo
      role_attribute_path: contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'

