#SPDX-License-Identifier: MIT-0
---
# tasks file for create_cluster

- name: Create a directory for the cluster configuration
  ansible.builtin.file:
    path: "{{ directory }}"
    state: directory

- name: Template the cluster configuration
  ansible.builtin.template:
    src: templates/config.yaml.j2
    dest: "{{ directory }}/config.yaml"

- name: Create a directory for the upstream registry override
  ansible.builtin.file:
    path: "{{ directory }}/certs.d/_default"
    state: directory

- name: Template the upstream override configuration
  ansible.builtin.template:
    src: templates/hosts.toml.j2
    dest: "{{ directory }}/certs.d/_default/hosts.toml"

- name: Copy the local CA into the containerd configuration
  ansible.builtin.copy:
    src: "{{ ca_file_path }}"
    dest: "{{ directory }}/certs.d/_default/ca.pem"
