#SPDX-License-Identifier: MIT-0
---
# tasks file for create_cluster

- name: Template cluster configuration
  ansible.builtin.template:
    src: templates/kind-config.yaml.j2
    dest: "{{ config_file }}"
