---
# TODO: We should register a name for postgres rather than connecting to ke-prometheus
- name: "Pre-installation of Kube Eng :: Keycloak"
  hosts: localhost
  tasks:

  - name: Create a user for Keycloak in PostgreSQL
    community.postgresql.postgresql_user:
      login_host: ke-prometheus.local
      login_user: postgres
      login_password: "{{ admin_password }}"
      login_db: postgres
      name: keycloak
      password: "{{ admin_password }}"
      comment: "Kube Eng :: Keycloak User"
      state: present
    environment:
      PGOPTIONS: "-c password_encryption=scram-sha-256"

  - name: Create a database for Keycloak in PostgreSQL
    community.postgresql.postgresql_db:
      login_host: ke-prometheus.local
      login_user: postgres
      login_password: "{{ admin_password }}"
      name: keycloak
      owner: keycloak
      comment: "Kube Eng :: Keycloak Database"
      encoding: UTF-8
      state: present
