#
# Playbook for provisioning a local Kubernetes cluster for engineering
---
- name: Create and maintain a Kubernetes cluster for local engineering
  hosts: localhost
  tasks:

  - name: Register Grafana client
    community.general.keycloak_client:
      auth_keycloak_url: http://ke-kc.local
      auth_realm: master
      auth_username: admin
      auth_password: "{{ admin_password }}"
      client_id: mrmat_grafana
      name: mrmat-grafana
      description: "MrMat :: Grafana"
      enabled: true
      protocol: openid-connect
      public_client: false
      client_authenticator_type: client-secret
      secret: "{{ admin_password }}"
      root_url: "http://mrmat-grafana.local/"
      base_url: "http://mrmat-grafana.local/"
      admin_url: "http://mrmat-grafana.local/"
      redirect_uris:
      - "http://mrmat-grafana.local/login/generic_oauth"
      standard_flow_enabled: true
      implicit_flow_enabled: false
      direct_access_grants_enabled: true
      default_client_scopes:
      - email
      - offline_access
      - profile
      - roles

  - name: Register Grafana Viewer role
    community.general.keycloak_role:
      auth_keycloak_url: http://ke-kc.local
      auth_realm: master
      auth_username: admin
      auth_password: "{{ admin_password }}"
      name: Viewer
      description: Grafana Viewers
      client_id: mrmat_grafana
      state: present

  - name: Register Grafana Editor role
    community.general.keycloak_role:
      auth_keycloak_url: http://ke-kc.local
      auth_realm: master
      auth_username: admin
      auth_password: "{{ admin_password }}"
      name: Editor
      description: Grafana Editors
      client_id: mrmat_grafana
      state: present

  - name: Register Grafana Admin role
    community.general.keycloak_role:
      auth_keycloak_url: http://ke-kc.local
      auth_realm: master
      auth_username: admin
      auth_password: "{{ admin_password }}"
      name: Admin
      description: Grafana Admins
      client_id: mrmat_grafana
      state: present

  - name: Register Kiali client
    community.general.keycloak_client:
      auth_keycloak_url: http://ke-kc.local
      auth_realm: master
      auth_username: admin
      auth_password: "{{ admin_password }}"
      client_id: mrmat-kiali
      name: mrmat-kiali
      description: "MrMat :: Kiali"
      enabled: true
      protocol: openid-connect
      public_client: false
      client_authenticator_type: client-secret
      secret: "{{ admin_password }}"
      root_url: "http://mrmat-kiali.local/"
      base_url: "http://mrmat-kiali.local/"
      admin_url: "http://mrmat-kiali.local/"
      redirect_uris:
      - "http://mrmat-kiali.local/login/generic_oauth"
      standard_flow_enabled: true
      implicit_flow_enabled: false
      direct_access_grants_enabled: true
      default_client_scopes:
      - email
      - offline_access
      - profile
      - roles