{{- if eq .Values.cluster.edge.kind "istio-gateway-api" }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: tempo-grpc
  labels:
    {{ include "common.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ .Values.cluster.edge.gateway.name }}
    namespace: {{ .Values.cluster.edge.gateway.ns }}
    sectionName: tempo-grpc  # The GRPC OTLP listener
  hostnames:
  - {{ .Values.cluster.edge.fqdn }}
  rules:
  - backendRefs:
    - name: tempo
      port: 4317
{{- end }}