#
# Default values for Kube Eng :: Keycloak

cluster:
  name: cluster
  edge:
    kind: istio-gateway-api
    fqdn: keycloak.cluster.k8s
    gateway:
      name: edge-gateway
      ns: edge
      section: keycloak

keycloak:
  instances: 1
  db: postgres
  db_user: keycloak
  db_password: admin
  db_host: kube-eng-postgres-svc.kube-eng.svc.cluster.local
  db_port: 5432
  db_database: keycloak
  port: 8080
  managementPort: 9000
  admin_user: admin
  admin_password: admin
