# Argument requirements. See https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#argument-spec
---
argument_specs:
  main:
    short_description: Create a namespace
    options:
      name:
        description: Name of the namespace
        type: str
        required: true
      mesh:
        description: The mesh in use
        type: str
        required: false
        choices: ['none', 'istio', 'istio-ambient']
        default: istio
