#
# Default values for Kube Eng :: Kiali

cluster:
  mesh: istio
  gateway_api: true
  name: cluster
  domain: local

edge:
  ns: edge
  name: edge-ingress
  kind: istio
  ingress_class: traefik

route:
  name: route-kiali
  hostname: kiali
  sectionName: kiali

prometheus:
  ns: prometheus
  hostname: prometheus

jaeger:
  ns: jaeger
  hostname: jaeger

grafana:
  ns: grafana
  hostname: grafana
  auth:
    type: bearer
    token: null
    username: null
    password: null

# To authenticate to Grafana, create a service account, set type to 'bearer' and specify the token.
# alternatively, set token to 'basic' and specify username and password