apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pod.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.pod.name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  replicas: {{ .Values.pod.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      version: {{ .Chart.Version }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        version: {{ .Chart.Version }}
        app.kubernetes.io/name: {{ .Values.pod.name }}
        app.kubernetes.io/part-of: {{ .Release.Name }}
        sidecar.istio.io/inject: "true"
      annotations:
        prometheus.io/scrape: "false"
    spec:
      serviceAccountName: {{ .Values.sa.name }}
      containers:
      - name: pg
        image: {{ .Values.pod.repository }}:{{ .Chart.AppVersion }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.pod.admin_user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.pod.admin_password }}
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }}

