apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pod.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.pod.name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  replicas: {{ .Values.pod.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      version: {{ .Chart.Version }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        version: {{ .Chart.Version }}
        app.kubernetes.io/name: {{ .Values.pod.name }}
        app.kubernetes.io/part-of: {{ .Release.Name }}
        sidecar.istio.io/inject: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.pod.managementPort | quote }}
        prometheus.io/path: '/metrics'
    spec:
      serviceAccountName: {{ .Values.sa.name }}
      containers:
      - name: kc
        image: {{ .Values.pod.repository }}:{{ .Chart.AppVersion }}
        args: ["start-dev"]
        env:
        - name: KC_HOSTNAME
          value: "http://{{ .Values.route.hostname }}"
        - name: KC_HOSTNAME_BACKCHANNEL_DYNAMIC
          value: "true"
        - name: KC_HOSTNAME_DEBUG
          value: "true"
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: {{ .Values.pod.admin_user }}
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          value: {{ .Values.pod.admin_password | quote }}
        - name: KC_PROXY_HEADERS
          value: "xforwarded"
        - name: KC_FEATURES
          value: "account:v3,account-api,admin:v2,admin-api,authorization,ciba,client-policies,device-flow,impersonation,opentelemetry,organization,par,passkeys,persistent-user-sessions,step-up-authentication,web-authn,hostname:v2,login:v2"
        - name: KC_LOG
          value: "console"
        - name: KC_LOG_CONSOLE_COLOR
          value: "true"
        - name: KC_LOG_CONSOLE_LEVEL
          value: "info"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: KC_METRICS_ENABLED
          value: "true"
        - name: KC_MANAGEMENT_PORT
          value: {{ .Values.pod.managementPort | quote }}
        ports:
        - name: http
          containerPort: {{ .Values.pod.port }}
          protocol: TCP
        - name: management
          containerPort: {{ .Values.pod.managementPort }}
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health/ready/
            port: {{ .Values.pod.managementPort }}
        livenessProbe:
          httpGet:
            path: /health/live/
            port: {{ .Values.pod.managementPort }}
