#
# Default values for Kube Eng :: Tempo

cluster:
  name: cluster
  edge:
    kind: istio-gateway-api
    fqdn: tempo.cluster.k8s
    gateway:
      name: edge
      ns: edge
      section: tempo

tempo:
  tempo:
    reportingEnabled: false
    metricsGenerator:
      enabled: false
    storage:
      trace:
        backend: s3
        s3:
          bucket: tempo-traces
          endpoint: "https://s3.kind:9000"
          access_key: null
          secret_key: null
          region: us-east-1
          insecure: false
          # TODO: Inject the CA
          tls_insecure_skip_verify: true

  serviceMonitor:
    enabled: true
    additionalLabels:
      app.kubernetes.io/monitored-by: prometheus
  networkPolicy:
    enabled: false
